// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { importProvidersFrom } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { KycRecordComponent } from '@views/kyc/kyc-record';

import { AuthenticationGuard } from '@app/auth/authentication.guard';

import { KycRecordControllerImpl } from '@controllers/kyc/kyc-record-controller-impl';
import { KycRecordApi } from '@services/bw/co/centralkyc/kyc/kyc-record-api';
import { KycRecordDetails } from './details/kyc-record-details';
import { UseCaseScope } from '@app/utils/use-case-scope';

export const kycRecordRoutes: Routes = [
  {
    path: 'kyc',
    component: KycRecordComponent,
    canActivate: [AuthenticationGuard],
    data: { title: 'Kyc Record' },
    providers: [KycRecordControllerImpl, KycRecordApi, UseCaseScope],
  },
  {
    path: 'details',
    component: KycRecordDetails,
    canActivate: [AuthenticationGuard],
    data: { title: 'Kyc Record Details' },
    providers: [
      importProvidersFrom(RouterModule),
      KycRecordControllerImpl,
      KycRecordApi,
      UseCaseScope,
    ],
  },
  {
    path: 'details/{id}',
    component: KycRecordDetails,
    canActivate: [AuthenticationGuard],
    data: { title: 'Kyc Record Details' },
    providers: [
      importProvidersFrom(RouterModule),
      KycRecordControllerImpl,
      KycRecordApi,
      UseCaseScope,
    ],
  },
];
