// Generated by andromda-angular cartridge (usecase\use-case.ts.vsl) DO NOT EDIT
import { 
    OnInit, 
    inject, 
    Component, 
    AfterViewInit,
    signal,
    Signal,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { KycRecordControllerImpl } from '@controllers/kyc/kyc-record-controller-impl';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { KycRecordApi } from '@services/bw/co/centralkyc/kyc/kyc-record-api';
import { KycRecordApiStore } from '@store/bw/co/centralkyc/kyc/kyc-record-api.store';

@Component({
  selector: 'app-kyc-record',
  templateUrl: './kyc-record.html',
  styleUrls: ['./kyc-record.scss'],
  standalone: true,
  imports: [
  ],
})
export class KycRecordComponent implements OnInit, AfterViewInit {

    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
        readonly kycRecordApi = inject(KycRecordApi);
    readonly kycRecordApiStore = inject(KycRecordApiStore);
    loaderMessage: Signal<string> = signal('');
    messages: Signal<string[]> = signal([]);
    success: Signal<boolean> = signal(false);
    loading: Signal<boolean> = signal(false);
    error: Signal<boolean> = signal(false);
    selected: Signal<any> = signal(null);

    constructor() {
    }
	
    ngOnInit() {
    }

    ngAfterViewInit() {
    }

}