// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditIndividualComponent } from '@views/individual/edit/edit-individual';
import { EditIndividualVarsForm } from '@views/individual/edit/edit-individual';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';

@Component({
  selector: 'app-edit-individual',
  templateUrl: './edit-individual.html',
  styleUrls: ['./edit-individual.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class EditIndividualImplComponent extends EditIndividualComponent {

    constructor() {
        super();
    }

    doNgOnDestroy(): void {
    }
}