// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, computed, effect, inject, Input, linkedSignal } from '@angular/core';
import { EditIndividualComponent } from '@views/individual/edit/edit-individual';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';
import { OrganisationApiStore } from '@app/store/bw/co/centralkyc/organisation/organisation-api.store';
import { BranchApiStore } from '@app/store/bw/co/centralkyc/organisation/branch/branch-api.store';
import { SearchObject } from '@app/models/search-object';
import { OrganisationSearchCriteria } from '@app/models/bw/co/centralkyc/organisation/organisation-search-criteria';
import { OrganisationListDTO } from '@app/models/bw/co/centralkyc/organisation/organisation-list-dto';
import { BranchDTO } from '@app/models/bw/co/centralkyc/organisation/branch/branch-dto';
import { PhoneNumber } from '@app/models/bw/co/centralkyc/phone-number';

@Component({
  selector: 'app-edit-individual',
  templateUrl: './edit-individual.html',
  styleUrls: ['./edit-individual.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    Loader,
    Field,
  ],
})
export class EditIndividualImplComponent extends EditIndividualComponent {

  @Input() id: string | any;

  organisationApiStore = inject(OrganisationApiStore);
  branchApiStore = inject(BranchApiStore);

  override loading = computed(
    () => this.individualApiStore.loading() || this.organisationApiStore.loading() || this.branchApiStore.loading(),
  );

  organisationList = linkedSignal(() => this.organisationApiStore.dataList());
  branchList = linkedSignal(() => this.branchApiStore.dataList())

  override error = linkedSignal(() => this.individualApiStore.error());
  override messages = linkedSignal(() => this.individualApiStore.messages());
  override success = linkedSignal(() => this.individualApiStore.success());

  individual = this.individualApiStore.data;

  constructor() {
    super();

    effect(() => {
      let individual = this.individualApiStore.data();

      if(!individual) {

        return;
      }

      this.editIndividualSignal.update((value) => ({
        ...individual
      }));

      if (individual.hasUser) {
        if (individual.organisation?.id) {
          this.organisationList.set([individual.organisation]);

        }

        if(individual?.branch?.id) {
          this.branchList.set([individual.branch]);
        }

      }

    });
  }

  override ngOnInit() {
    this.individualApiStore.reset();

    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.individualApiStore.findById(params);
      }
    });

  }

  doNgOnDestroy(): void {}

  override beforeEditIndividualSave(form: any): void {
    this.individualApiStore.save({ individual: this.editIndividualSignal() });
  }

  override filterOrganisation(): void {
    let criteria = new SearchObject<OrganisationSearchCriteria>();
    criteria.criteria = {
      registrationNo: this.editIndividualSignal().organisationFilter || '',
      name: this.editIndividualSignal().organisationFilter || ''
    }
    this.organisationApiStore.search({ criteria: criteria });
  }

  override filterBranch(): void {
    let criteria = this.editIndividualSignal().branchFilter || '';
    let organisationId = this.editIndividualSignal().organisation?.id;

    this.branchApiStore.findByOrganisation({ organisationId: organisationId });
  }

  override organisationCompare(o1: OrganisationListDTO | any, o2: OrganisationListDTO | any) {
    return o1 && o2 ? o1.id === o2.id : false;
  }

  override branchCompare(o1: BranchDTO | any, o2: BranchDTO | any) {
    return o1 && o2 ? o1.id === o2.id : false;
  }

  createNewPhoneNumbers(): PhoneNumber {

    return new PhoneNumber()
  }
}
