// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycRecordDTO } from '@app/model/bw/co/centralkyc/kyc/kyc-record-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class KycRecordApi {
    
    protected path = '/kyc';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<KycRecordDTO | any> {

        return this.http.get<KycRecordDTO | any>(`${this.path}/${id}`);
    }

    public findByIdentityNo(identityNo: string | any ): Observable<KycRecordDTO[] | any[]> {

        return this.http.get<KycRecordDTO[] | any[]>(`${this.path}/by-identity/${identityNo}`);
    }

    public findByIndividual(individualId: string | any ): Observable<KycRecordDTO[] | any[]> {

        return this.http.get<KycRecordDTO[] | any[]>(`${this.path}/by-individual/${individualId}`);
    }

    public getAll(): Observable<KycRecordDTO[] | any[]> {

        return this.http.get<KycRecordDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<KycRecordDTO> | any> {

        return this.http.get<Page<KycRecordDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<KycRecordDTO> | any> {

        return this.http.get<Page<KycRecordDTO> | any>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(kycRecord: KycRecordDTO | any ): Observable<KycRecordDTO | any> {

        return this.http.post<KycRecordDTO | any>(`${this.path}`, kycRecord);
    }

    public search(criteria: string | any ): Observable<KycRecordDTO[] | any[]> {

        return this.http.get<KycRecordDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
