// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, Input, linkedSignal, Signal } from '@angular/core';
import { EditOrganisationComponent } from '@views/organisation/edit/edit-organisation';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';
import { RouterLink, RouterModule } from "@angular/router";

@Component({
  selector: 'app-edit-organisation',
  templateUrl: './edit-organisation.html',
  styleUrls: ['./edit-organisation.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
    RouterModule
],
})
export class EditOrganisationImplComponent extends EditOrganisationComponent {
  @Input() id: string = '';
  override error = linkedSignal(() => this.organisationApiStore.error());
  override messages = linkedSignal(() => this.organisationApiStore.messages());
  override success = linkedSignal(() => this.organisationApiStore.success());
  override loading = linkedSignal(() => false);
  override loaderMessage = linkedSignal(() => '');

  constructor() {
    super();

    effect(() => {
      let organisation = this.editOrganisationSignal();
      // this.editOrganisationForm.patchValue(organisation);
    });

    // Handle form control disabled state based on loading
    effect(() => {
      const isLoading = this.loading();

    });
  }

  override ngOnInit() {
    // this.organisationApiStore.reset();

    this.route.queryParams.subscribe(params => {
      const id = params['id'];
      if (id) {
        this.id = id;
        this.organisationApi.findById(id).subscribe((organisationData) => {
          this.editOrganisationSignal.set(organisationData);
        });
      }
    });

  }

  doNgOnDestroy(): void { }

  override beforeEditOrganisationSave(form: any): void {

    this.loading.set(true);
    this.loaderMessage.set(`Saving organisation ${this.editOrganisationSignal().name}.`)

    this.organisationApi.save(this.editOrganisationSignal()).subscribe({
      next: (response) => {
        this.editOrganisationSignal.set(response);
        this.toaster.success('organisation.save.success');
        this.loading.set(false);
        this.router.navigate(['/organisations']);
      },
      error: (error) => {
        this.toaster.error('organisation.save.error');
        this.loading.set(false);
      }
    });
  }
}
