// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, Input, linkedSignal, Signal } from '@angular/core';
import { EditOrganisationComponent } from '@views/organisation/edit/edit-organisation';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { RouterLink, RouterModule } from "@angular/router";
import { PhoneNumber } from '@app/models/bw/co/centralkyc/phone-number';
import { OrganisationDomain } from '@app/models/bw/co/centralkyc/organisation/organisation-domain';
import { OrganisationDTO } from '@app/models/bw/co/centralkyc/organisation/organisation-dto';

@Component({
  selector: 'app-edit-organisation',
  templateUrl: './edit-organisation.html',
  styleUrls: ['./edit-organisation.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    Loader,
    FormField,
    RouterModule
],
})
export class EditOrganisationImplComponent extends EditOrganisationComponent {
  @Input() id: string = '';
  override error = linkedSignal(() => this.organisationApiStore.error());
  override messages = linkedSignal(() => this.organisationApiStore.messages());
  override success = linkedSignal(() => this.organisationApiStore.success());
  override loading = linkedSignal(() => this.organisationApiStore.loading());
  override loaderMessage = linkedSignal(() => this.organisationApiStore.loaderMessage());

  constructor() {
    super();

    effect(() => {
      let organisation = this.organisationApiStore.data() || new OrganisationDTO();

      console.log(organisation)
      this.editOrganisationSignal.update((value) => ({
        ...organisation
      }))
    });
  }

  override ngOnInit() {
    this.organisationApiStore.reset();

    this.route.queryParams.subscribe(params => {
      const id = params['id'];
      if (id) {
        this.id = id;
        this.organisationApiStore.findById({id: id});
      }
    });

  }

  doNgOnDestroy(): void { }

  override beforeEditOrganisationSave(form: any): void {

    this.editOrganisationSignalForm().invalid()

    let value = this.editOrganisationSignal();
    let org = {
      code: value.code,
      description: value.description,
      domains: value.domains,
      phoneNumbers: value.phoneNumbers,
      status: value.status,
      postalAddress: value.postalAddress,
      physicalAddress: value.physicalAddress,
      contactEmailAddress: value.contactEmailAddress,
      name: value.name,
      registrationNo: value.registrationNo,
      createdAt: value.createdAt,
      createdBy: value.createdBy,
      modifiedAt: value.modifiedAt,
      modifiedBy: value.modifiedBy,
      isClient: value.isClient,
      kycStatus: value.kycStatus,
      countryOfRegistration: value.countryOfRegistration,
      id: value.id
    } as OrganisationDTO;

    this.organisationApiStore.save({organisation: org});
  }
}
