// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::IdentityType
 */
export enum IdentityType {
    /** TODO: Model Documentation for Enumeration Literal OMANG value "OMANG" */
    OMANG = "OMANG",
    /** TODO: Model Documentation for Enumeration Literal PASSPORT value "PASSPORT" */
    PASSPORT = "PASSPORT",
    /** TODO: Model Documentation for Enumeration Literal CIPA value "CIPA" */
    CIPA = "CIPA"
}
