// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::PhoneType
 */
export enum PhoneType {
    /** TODO: Model Documentation for Enumeration Literal MOBILE value "MOBILE" */
    MOBILE = "MOBILE",
    /** TODO: Model Documentation for Enumeration Literal WORK value "WORK" */
    WORK = "WORK",
    /** TODO: Model Documentation for Enumeration Literal HOME value "HOME" */
    HOME = "HOME",
    /** TODO: Model Documentation for Enumeration Literal MAIN value "MAIN" */
    MAIN = "MAIN",
    /** TODO: Model Documentation for Enumeration Literal OTHER value "OTHER" */
    OTHER = "OTHER"
}
