// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, computed, effect, inject, linkedSignal } from '@angular/core';
import { EditSettingsComponent } from '@views/settings/edit-settings';
import { EditSettingsVarsForm } from '@views/settings/edit-settings';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from '@shared/loader/loader';
import { Field } from '@angular/forms/signals';
import { SettingsApi } from '@app/services/bw/co/centralkyc/settings/settings-api';
import { DocumentTypeApi } from '@app/services/bw/co/centralkyc/document/type/document-type-api';
import { DocumentApi } from '@app/services/bw/co/centralkyc/document/document-api';
import { DocumentTypeDTO } from '@app/models/bw/co/centralkyc/document/type/document-type-dto';
import { SettingsDTO } from '@app/models/bw/co/centralkyc/settings/settings-dto';
import { TargetEntity } from '@app/models/bw/co/centralkyc/target-entity';

@Component({
  selector: 'app-edit-settings',
  templateUrl: './edit-settings.html',
  styleUrls: ['./edit-settings.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class EditSettingsImplComponent extends EditSettingsComponent {
  // settingApiStore = inject(SettingsApiStore);
  settingApi = inject(SettingsApi);
  // settingsSignal = linkedSignal(() => new SettingsDTO());
  // documentTypeApiStore = inject(DocumentTypeApiStore);
  documentTypeApi = inject(DocumentTypeApi);
  documentApi = inject(DocumentApi);

  override organisationDocumentsTableSignal = computed<DocumentTypeDTO[]>(() => []);
  override individualDocumentsTableSignal = computed<DocumentTypeDTO[]>(() => []);
  override orgKycDocumentsTableSignal = computed<DocumentTypeDTO[]>(() => []);
  override indKycDocumentsTableSignal = computed<DocumentTypeDTO[]>(() => []);

  override loading = linkedSignal(() => false);
  override error = linkedSignal(() => false);
  override messages = linkedSignal(() => false);
  override success = linkedSignal(() => false);

  settings: SettingsDTO = new SettingsDTO();

  constructor() {
    super();

    effect(() => {
      this.settings = this.editSettingsSignal();
      // this.editSettingsForm.patchValue(this.settings);

      if (this.settings.invoiceDocumentType && this.settings.invoiceDocumentType.id) {
        this.invoiceDocumentTypeFilteredList.set([this.settings.invoiceDocumentType || null]);
      }

      if (this.settings.invoiceTemplateType && this.settings.invoiceTemplateType.id) {
        this.invoiceTemplateTypeFilteredList.set([this.settings.invoiceTemplateType]);
      }

      if (this.settings.quotationDocumentType && this.settings.quotationDocumentType.id) {
        this.quotationDocumentTypeFilteredList.set([this.settings.quotationDocumentType]);
      }

      if (this.settings.quotationTemplateType && this.settings.quotationTemplateType.id) {
        this.quotationTemplateTypeFilteredList.set([this.settings.quotationTemplateType]);
      }

      if (this.settings.clientRequestFileType && this.settings.clientRequestFileType.id) {
        this.clientRequestFileTypeFilteredList.set([this.settings.clientRequestFileType]);
      }
    });
  }

  override ngOnInit() {
    // this.settingApiStore.reset();
    // this.settingApiStore.getAll();

    this.settingApi.getAll().subscribe({
      next: (settings: SettingsDTO[]) => {
        if ((settings || []).length > 0) {
          this.updateSettingForm(settings[0]);
        }
      },
    });

    // this.organisationDocumentsTablePaged.set(false);
    // this.individualDocumentsTablePaged.set(false);
    // this.orgKycDocumentsTablePaged.set(false);
    // this.indKycDocumentsTablePaged.set(false);

    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.loading.set(true);
        this.loaderMessage.set(`Loading settings`);
        this.settingApi.findById(params.id).subscribe({
          next: (settings: SettingsDTO) => {
            // this.settingsSignal.set(settings);
            this.updateSettingForm(settings);
            this.loading.set(false);
          },
          error: (error) => {
            this.toaster.error(error.error?.message ? error.error.message : error.message);
            this.loading.set(false);
          },
        });
      }
    });
  }

  doNgOnDestroy(): void {}

  updateSettingForm(settings: SettingsDTO) {
    this.editSettingsSignal.set({
      id: settings.id,
      createdAt: settings.createdAt,
      createdBy: settings.createdBy,
      modifiedAt: settings.modifiedAt,
      modifiedBy: settings.modifiedBy,
      kycDuration: settings.kycDuration,
      selectedOrgDocument: null,
      organisationDocuments: settings.organisationDocuments || [],
      selectedKycOrgDocument: null,
      orgKycDocuments: settings.orgKycDocuments || [],
      selectedIndDocument: null,
      individualDocuments: settings.individualDocuments || [],
      selectedKycIndDocument: null,
      indKycDocuments: settings.indKycDocuments || [],
      invoiceDocumentType: null,
      invoiceTemplateType: settings.invoiceTemplateType,
      invoiceTemplate: settings.invoiceTemplate,
      quotationDocumentType: settings.quotationDocumentType,
      quotationTemplateType: settings.quotationTemplateType,
      quotationTemplate: settings.quotationTemplate,
      clientRequestFileType: settings.clientRequestFileType,
    });
  }

  private getSettings(value: any): SettingsDTO {
    let settings: SettingsDTO = {};
    settings.createdAt = value.createdAt;
    settings.createdBy = value.createdBy;
    settings.modifiedAt = value.modifiedAt;
    settings.modifiedBy = value.modifiedBy;
    settings.id = value.id;
    settings.kycDuration = value.kycDuration;
    settings.organisationDocuments = value.organisationDocuments || [];
    settings.individualDocuments = value.individualDocuments || [];
    settings.indKycDocuments = value.indKycDocuments || [];
    settings.orgKycDocuments = value.orgKycDocuments || [];
    settings.invoiceDocumentType = value.invoiceDocumentType;
    settings.clientRequestFileType = value.clientRequestFileType;
    settings.invoiceTemplateType = value.invoiceTemplateType;
    settings.invoiceTemplate = value.invoiceTemplate;
    settings.quotationDocumentType = value.quotationDocumentType;
    settings.quotationTemplateType = value.quotationTemplateType;
    settings.quotationTemplate = value.quotationTemplate;

    return settings;
  }

  override beforeEditSettingsSave(form: any): void {
    let val: any = this.editSettingsSignal();
    let settings = this.getSettings(val);
    this.loading.set(true);
    this.loaderMessage.set(`Saving settings`);
    this.settingApi.save(settings).subscribe({
      next: (settings: SettingsDTO) => {
        // this.settingsSignal.set(settings);
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
  }

  override filterSelectedOrgDocument(): void {
    const search = this.selectedOrgDocumentFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.selectedOrgDocumentFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterInvoiceDocumentType(): void {
    const search = this.invoiceDocumentTypeFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.invoiceDocumentTypeFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterClientRequestFileType(): void {
    const search = this.clientRequestFileTypeFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.clientRequestFileTypeFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterInvoiceTemplateType(): void {
    const search = this.invoiceTemplateTypeFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.invoiceTemplateTypeFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterQuotationDocumentType(): void {
    const search = this.quotationDocumentTypeFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.quotationDocumentTypeFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterQuotationTemplateType(): void {
    const search = this.quotationTemplateTypeFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.quotationTemplateTypeFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterSelectedKycOrgDocument(): void {
    const search = this.selectedKycOrgDocumentFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.selectedKycOrgDocumentFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterSelectedIndDocument(): void {
    const search = this.selectedIndDocumentFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.selectedIndDocumentFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override filterSelectedKycIndDocument(): void {
    const search = this.selectedKycIndDocumentFilterCtrl.value?.toLowerCase() || '';
    this.loading.set(true);
    this.loaderMessage.set(`Searching document types.`);
    this.documentTypeApi.search(search).subscribe(
      (data) => {
        this.selectedKycIndDocumentFilteredList.set(data || []);
        this.loading.set(false);
      },
      (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      }
    );
  }

  override onAddToIndDocumentsClick() {
    console.log(this.selectedIndDocumentControl.value);
    let val: any = this.editSettingsSignal();
    let settings = this.getSettings(val);
    let found = settings.individualDocuments?.find(
      (d) => d.id === this.selectedIndDocumentControl.value.id
    );
    if (!found) {
      settings.individualDocuments?.push(this.selectedIndDocumentControl.value);
    }
    this.settingApi.save(settings).subscribe({
      next: (settings: SettingsDTO) => {
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
    this.selectedIndDocumentControl.setValue(null);
  }

  override onAddToKycOrgDocumentsClick() {
    console.log(this.selectedKycOrgDocumentControl.value);
    let val: any = this.editSettingsSignal();
    let settings: SettingsDTO = this.getSettings(val);
    let found = settings.orgKycDocuments?.find(
      (d) => d.id === this.selectedKycOrgDocumentControl.value.id
    );
    if (!found) {
      settings.orgKycDocuments?.push(this.selectedKycOrgDocumentControl.value);
    }
    this.settingApi.save(settings).subscribe({
      next: (settings: SettingsDTO) => {
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
    this.selectedKycOrgDocumentControl.setValue(null);
  }

  override onAddToOrgDocumentsClick() {
    console.log(this.selectedOrgDocumentControl.value);
    let val: any = this.editSettingsSignal();
    let settings: SettingsDTO = this.getSettings(val);
    let found = settings.organisationDocuments?.find((d) => d.id === this.selectedOrgDocumentControl.value.id);
    if (!found) {
      settings.organisationDocuments?.push(this.selectedOrgDocumentControl.value);
    }
    this.settingApi.save(settings).subscribe({
      next: (settings: SettingsDTO) => {
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
    this.selectedOrgDocumentControl.setValue(null);
  }

  override onAddToKycIndDocumentsClick() {
    console.log(this.selectedKycIndDocumentControl.value);
    let val: any = this.editSettingsSignal();
    let settings: SettingsDTO = this.getSettings(val);
    let found = settings.indKycDocuments?.find((d) => d.id === this.selectedKycIndDocumentControl.value.id);
    if (!found) {
      settings.indKycDocuments?.push(this.selectedKycIndDocumentControl.value);
    }
    this.settingApi.save(settings).subscribe({
      next: (settings: SettingsDTO) => {
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
    this.selectedKycIndDocumentControl.setValue(null);
  }

  attachInvoiceTemplate(): void {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept =
      'application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    input.onchange = (event: any) => {
      const file = event.target.files[0];
      if (file) {
        this.handleInvoiceTemplateUpload(file);
      }
    };
    input.click();
  }

  attachQuotationTemplate(): void {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept =
      'application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    input.onchange = (event: any) => {
      const file = event.target.files[0];
      if (file) {
        this.handleQuotationTemplateUpload(file);
      }
    };
    input.click();
  }

  private handleInvoiceTemplateUpload(file: File): void {
    // TODO: Implement invoice template upload logic
    console.log('Invoice template upload:', file.name);

    this.settingApi.uploadTemplate(file, TargetEntity.INVOICE).subscribe({
      next: (settings: SettingsDTO) => {
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
  }

  private handleQuotationTemplateUpload(file: File): void {
    // TODO: Implement quotation template upload logic
    console.log('Quotation template upload:', file.name);

    this.settingApi.uploadTemplate( file, TargetEntity.QUOTATION).subscribe({
      next: (settings: SettingsDTO) => {
        this.updateSettingForm(settings);
        this.loading.set(false);
      },
      error: (error) => {
        this.toaster.error(error.error?.message ? error.error.message : error.message);
        this.loading.set(false);
      },
    });
  }

  downloadTemplate(target: TargetEntity): void {
    if (target === TargetEntity.INVOICE) {
    } else if (target === TargetEntity.QUOTATION) {
    }

    const docId =
      target === TargetEntity.INVOICE
        ? this.editSettingsSignal().invoiceTemplate?.id
        : this.editSettingsSignal().quotationTemplate?.id;

    if (!docId) {
      this.toaster.error('No template document available for download', 'Download Error');
      return;
    }

    let doc =
      target === TargetEntity.INVOICE
        ? this.settings.invoiceTemplate
        : this.settings.quotationTemplate;

    this.documentApi.downloadFile(doc?.id).subscribe({
      next: (res: any) => {
        const url = window.URL.createObjectURL(res);
        const a = document.createElement('a');
        a.href = url;

        // Optional: set a meaningful filename
        a.download = `${doc?.fileName}.pdf`; // or dynamically get filename from backend
        a.click();

        window.URL.revokeObjectURL(url); // clean up
      },
      error: (err: any) => {
        this.toaster.error(err.message || 'Failed to download file', 'Download Error');
      },
      complete: () => {
        // this.isDownloading.set('');
      },
    });
  }
}
