// Generated by andromda-angular cartridge (view\view.component.ts.vsl) DO NOT EDIT
import {
  Component,
  OnInit,
  effect,
  inject,
  ViewChild,
  Input,
  Output,
  EventEmitter,
  AfterViewInit,
  signal,
  Signal,
  linkedSignal,
  WritableSignal,
  OnDestroy,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { FormGroup, FormControl, FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { formatDate } from '@angular/common';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { Store, select } from '@ngrx/store';
import { Observable, of, Subscription } from 'rxjs';
import { SearchObject } from '@app/model/search-object';
import { MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';
import { MatChipInputEvent } from '@angular/material/chips';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { TableComponent } from '@app/components/table/table.component';
import { OrganisationApiStore } from '@app/store/bw/co/centralkyc/organisation/organisation-api.store';
import { ColumnModel } from '@app/model/column.model';
import { ActionTemplate } from '@app/model/action-template';

import { OrganisationApi } from '@app/service/bw/co/centralkyc/organisation/organisation-api';
import { OrganisationDTO } from '@app/model/bw/co/centralkyc/organisation/organisation-dto';
import { OrganisationListDTO } from '@app/model/bw/co/centralkyc/organisation/organisation-list-dto';
import { OrganisationDomain } from '@app/model/bw/co/centralkyc/organisation/organisation-domain';
import { DocumentDTO } from '@app/model/bw/co/centralkyc/document/document-dto';
import { OrganisationControllerImpl } from '@app/controller/organisation/organisation-controller.impl';
import { DocumentTypeDTO } from '@app/model/bw/co/centralkyc/document/type/document-type-dto';
import { GeneralStatus } from '@app/model/bw/co/centralkyc/general-status';
import { ToastrService } from 'ngx-toastr';
import { Page } from '@app/model/page.model';

export class EditOrganisationVarsForm {
  id?: string | any;
  createdAt?: Date | any;
  createdBy?: string | any;
  modifiedAt?: Date | any;
  modifiedBy?: string | any;
  status?: GeneralStatus | any;
  registrationNo?: string | any;
  code?: string | any;
  name?: string | any;
  description?: string | any;
  phoneNumbers?: any[] | any[];
  contactEmailAddress?: string | any;
  postalAddress?: string | any;
  physicalAddress?: string | any;
  domains?: OrganisationDomain[] | any = []
}

@Component({
  selector: 'app-edit-organisation-base',
  template: '',
})
export abstract class EditOrganisationComponent implements OnInit, AfterViewInit, OnDestroy {
  separatorKeysCodes: number[] = [ENTER, COMMA];
  @Input() editOrganisationVarsForm: EditOrganisationVarsForm = {};

  editOrganisationForm: FormGroup = new FormGroup({});
  hide: boolean = false;
  protected route: ActivatedRoute = inject(ActivatedRoute);
  protected router: Router = inject(Router);
  protected formBuilder: FormBuilder = inject(FormBuilder);
  protected useCaseScope: UseCaseScope = inject(UseCaseScope);
  dialog: MatDialog = inject(MatDialog);
  toaster: ToastrService = inject(ToastrService);
  organisationController: OrganisationControllerImpl = inject(OrganisationControllerImpl);
  readonly organisationApiStore = inject(OrganisationApiStore);

  GeneralStatusT: any = GeneralStatus;
  GeneralStatusOptions = Object.keys(this.GeneralStatusT);
  loaderMessage: Signal<string> = signal('');
  messages: Signal<string[]> = signal([]);
  success: Signal<boolean> = signal(false);
  loading: Signal<boolean> = signal(false);
  error: Signal<boolean> = signal(false);
  selected: Signal<any> = signal(null);
  deleteUnrestricted = signal(false);

  editOrganisationFormValueSubscription?: Subscription;

  constructor() {
    effect(() => {
      let messages = this.messages();

      if (this.success() && !this.loading()) {
        this.toaster.success(messages[0]);
      }

      if (this.error() && !this.loading()) {
        this.toaster.error(messages[0]);
      }
    });
  }

  abstract beforeOnInit(form: EditOrganisationVarsForm): EditOrganisationVarsForm;

  ngOnInit() {
    let form: EditOrganisationVarsForm = this.beforeOnInit(new EditOrganisationVarsForm());
    this.editOrganisationForm = this.newForm(form);

    console.log(this.editOrganisationForm)

    this.editOrganisationFormValueSubscription = this.editOrganisationForm.valueChanges.subscribe((change: any) => {
      this.handleFormChanges(change);
    });

    this.afterOnInit();
  }

  handleFormChanges(change: any): void {}

  editOrganisationFormReset() {
    this.editOrganisationForm.reset();
    this.editOrganisationForm.markAsPristine();

    if (this.router.url.substring(0, this.router.url.indexOf('?'))) {
      this.router.navigate([this.router.url.substring(0, this.router.url.indexOf('?'))]);
    } else {
      this.router.navigate([this.router.url]);
    }
  }

  afterOnInit(): void {}

  doNgAfterViewInit(): void {}

  ngAfterViewInit() {
    this.doNgAfterViewInit();
    this.organisationController.resetUseCaseScope();
  }

  newForm(editOrganisationVarsForm: EditOrganisationVarsForm): FormGroup {
    return this.formBuilder.group({
      id: [{ value: this.editOrganisationVarsForm.id, disabled: false }],
      createdAt: [{ value: this.editOrganisationVarsForm.createdAt, disabled: false }],
      createdBy: [{ value: this.editOrganisationVarsForm.createdBy, disabled: false }],
      modifiedAt: [{ value: this.editOrganisationVarsForm.modifiedAt, disabled: false }],
      modifiedBy: [{ value: this.editOrganisationVarsForm.modifiedBy, disabled: false }],
      status: [{ value: this.editOrganisationVarsForm.status, disabled: false }, [Validators.required]],
      registrationNo: [{ value: this.editOrganisationVarsForm.registrationNo, disabled: false }, [Validators.required]],
      code: [{ value: this.editOrganisationVarsForm.code, disabled: false }, [Validators.required]],
      name: [{ value: this.editOrganisationVarsForm.name, disabled: false }, [Validators.required]],
      description: [{ value: this.editOrganisationVarsForm.description, disabled: false }, [Validators.required]],
      phoneNumbers: [{ value: this.editOrganisationVarsForm.phoneNumbers || [], disabled: false }],
      contactEmailAddress: [{ value: this.editOrganisationVarsForm.contactEmailAddress, disabled: false }],
      postalAddress: [{ value: this.editOrganisationVarsForm.postalAddress, disabled: false }, [Validators.required]],
      physicalAddress: [
        { value: this.editOrganisationVarsForm.physicalAddress, disabled: false },
        [Validators.required],
      ],
      domains: this.createOrganisationDomainArray(this.editOrganisationVarsForm.domains)
    });
  }

  abstract doNgOnDestroy(): void;

  ngOnDestroy() {
    this.doNgOnDestroy();
    if (this.editOrganisationFormValueSubscription) {
      this.editOrganisationFormValueSubscription.unsubscribe();
    }
  }


  createOrganisationDomainGroup(value?: OrganisationDomain): FormGroup {
    return this.formBuilder.group({
      name: [value?.name, Validators.required],
      verified: [value?.verified ? value.verified : false],
    });
  }

  createOrganisationDomainArray(values?: OrganisationDomain[]): FormArray {
    if (values) {
      let formArray: FormArray = this.formBuilder.array([]);
      values?.forEach((value) => formArray.push(this.createOrganisationDomainGroup(value)));

      return formArray;
    } else {
      return new FormArray([] as any);
    }
  }

  /**
   * This method may be overwritten
   */
  beforeEditOrganisationSave(form: any): void {}

  /**
   * This method may be overwritten
   */
  afterEditOrganisationSave(form: any): void {}

  /**
   * This method may be overwritten
   */
  get editOrganisationSaveOrganisation(): OrganisationDTO {
    return {} as OrganisationDTO;
  }

  editOrganisationSave(): void {
    let form: any = {
      organisation: this.editOrganisationSaveOrganisation,
    };

    this.beforeEditOrganisationSave(form);

    this.organisationController.editOrganisationSave(form.organisation);
    this.afterEditOrganisationSave(form);
  }

  /**
   * This method may be overwritten
   */
  beforeEditOrganisationSearch(form: any): void {}

  /**
   * This method may be overwritten
   */
  afterEditOrganisationSearch(form: any): void {}

  editOrganisationSearch(): void {
    let form: any = {};

    this.beforeEditOrganisationSearch(form);

    this.organisationController.editOrganisationSearch();
    this.afterEditOrganisationSearch(form);
  }

  /**
   * This method may be overwritten
   */
  beforeEditOrganisationDelete(form: any): void {}

  /**
   * This method may be overwritten
   */
  afterEditOrganisationDelete(form: any): void {}

  /**
   * This method may be overwritten
   */
  get editOrganisationDeleteOrganisation(): OrganisationDTO {
    return {} as OrganisationDTO;
  }

  editOrganisationDelete(): void {
    let form: any = {
      organisation: this.editOrganisationDeleteOrganisation,
    };

    this.beforeEditOrganisationDelete(form);

    this.organisationController.editOrganisationDelete(form.organisation);
    this.afterEditOrganisationDelete(form);
  }

  get editOrganisationVarsFormControl(): FormGroup {
    return this.getGroupControl('editOrganisationVarsForm');
  }

  get idControl(): FormControl {
    return this.editOrganisationForm?.get('id') as FormControl;
  }

  get createdAtControl(): FormControl {
    return this.editOrganisationForm?.get('createdAt') as FormControl;
  }

  get createdByControl(): FormControl {
    return this.editOrganisationForm?.get('createdBy') as FormControl;
  }

  get modifiedAtControl(): FormControl {
    return this.editOrganisationForm?.get('modifiedAt') as FormControl;
  }

  get modifiedByControl(): FormControl {
    return this.editOrganisationForm?.get('modifiedBy') as FormControl;
  }

  get statusControl(): FormGroup {
    return this.editOrganisationForm?.get('status') as FormGroup;
  }

  get registrationNoControl(): FormControl {
    return this.editOrganisationForm?.get('registrationNo') as FormControl;
  }

  get codeControl(): FormControl {
    return this.editOrganisationForm?.get('code') as FormControl;
  }

  get nameControl(): FormControl {
    return this.editOrganisationForm?.get('name') as FormControl;
  }

  get descriptionControl(): FormControl {
    return this.editOrganisationForm?.get('description') as FormControl;
  }

  get phoneNumbersControl(): FormArray {
    return this.editOrganisationForm?.get('phoneNumbers') as FormArray;
  }

  get contactEmailAddressControl(): FormControl {
    return this.editOrganisationForm?.get('contactEmailAddress') as FormControl;
  }

  get postalAddressControl(): FormControl {
    return this.editOrganisationForm?.get('postalAddress') as FormControl;
  }

  get physicalAddressControl(): FormControl {
    return this.editOrganisationForm?.get('physicalAddress') as FormControl;
  }

  get domainsControl(): FormArray<FormGroup> {
    return this.editOrganisationForm?.get('domains') as FormArray<FormGroup>;
  }

  getItemControl(name: string): FormControl {
    return this.editOrganisationForm.get(name) as FormControl;
  }

  getGroupControl(name: string): FormGroup {
    return this.editOrganisationForm.get(name) as FormGroup;
  }

  getArrayControl(name: string): FormArray {
    return this.editOrganisationForm.get(name) as FormArray;
  }

  setEditOrganisationFormValue(form: any) {
    if (form.id) {
      this.editOrganisationForm?.get('id')?.setValue(form.id);
    }
    if (form.createdAt) {
      this.editOrganisationForm?.get('createdAt')?.setValue(form.createdAt);
    }
    if (form.createdBy) {
      this.editOrganisationForm?.get('createdBy')?.setValue(form.createdBy);
    }
    if (form.modifiedAt) {
      this.editOrganisationForm?.get('modifiedAt')?.setValue(form.modifiedAt);
    }
    if (form.modifiedBy) {
      this.editOrganisationForm?.get('modifiedBy')?.setValue(form.modifiedBy);
    }
    if (form.status) {
      this.editOrganisationForm?.get('status')?.setValue(form.status);
    }
    if (form.registrationNo) {
      this.editOrganisationForm?.get('registrationNo')?.setValue(form.registrationNo);
    }
    if (form.code) {
      this.editOrganisationForm?.get('code')?.setValue(form.code);
    }
    if (form.name) {
      this.editOrganisationForm?.get('name')?.setValue(form.name);
    }
    if (form.description) {
      this.editOrganisationForm?.get('description')?.setValue(form.description);
    }
    if (form.phoneNumbers) {
      this.editOrganisationForm?.get('phoneNumbers')?.setValue(form.phoneNumbers);
    }
    if (form.contactEmailAddress) {
      this.editOrganisationForm?.get('contactEmailAddress')?.setValue(form.contactEmailAddress);
    }
    if (form.postalAddress) {
      this.editOrganisationForm?.get('postalAddress')?.setValue(form.postalAddress);
    }
    if (form.physicalAddress) {
      this.editOrganisationForm?.get('physicalAddress')?.setValue(form.physicalAddress);
    }
  }
}
