// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, inject, Input, linkedSignal, Signal } from '@angular/core';
import { EditSubscriptionComponent } from '@app/view/subscription/edit-subscription.component';
import { EditSubscriptionVarsForm } from '@app/view/subscription/edit-subscription.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';
import { OrganisationApiStore } from '@app/store/bw/co/centralkyc/organisation/organisation-api.store';
import { OrganisationListDTO } from '@app/model/bw/co/centralkyc/organisation/organisation-list-dto';
import { SearchObject } from '@app/model/search-object';
import { OrganisationSearchCriteria } from '@app/model/bw/co/centralkyc/organisation/organisation-search-criteria';

@Component({
  selector: 'app-edit-subscription',
  templateUrl: './edit-subscription.component.html',
  styleUrls: ['./edit-subscription.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class EditSubscriptionImplComponent extends EditSubscriptionComponent {

  @Input() id: string | any;

  override loading = linkedSignal(() => this.kycSubscriptionApiStore.loading());
  organisationApiStore = inject(OrganisationApiStore);

  constructor() {
    super();

    this.kycSubscriptionApiStore.reset();
    if (this.id) {
      this.kycSubscriptionApiStore.findById({ id: this.id });
    }
  }

  override beforeOnInit(form: EditSubscriptionVarsForm): EditSubscriptionVarsForm {
    return form;
  }

  doNgOnDestroy(): void { }

  override beforeEditSubscriptionSave(form: any): void {
    this.kycSubscriptionApiStore.save({ subscription: this.editSubscriptionForm.value });
  }

  override organisationCompare(o1: OrganisationListDTO | any, o2: OrganisationListDTO | any) {
    return o1 && o2 ? o1.id === o2.id : o1 === o2;
  }

  override filterOrganisation() {

    let filter = this.organisationFilterCtrl.value?.toLowerCase() || '';

    let criteria: SearchObject<OrganisationSearchCriteria> = new SearchObject<OrganisationSearchCriteria>();
    criteria.criteria = { name: filter };

    this.organisationApiStore.search({ criteria });
  }
}
