// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, Input, linkedSignal } from '@angular/core';
import { EditOrganisationComponent } from '@app/view/organisation/edit-organisation.component';
import { EditOrganisationVarsForm } from '@app/view/organisation/edit-organisation.component';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { LoaderComponent } from '@app/@shared/loader/loader.component';

@Component({
  selector: 'app-edit-organisation',
  templateUrl: './edit-organisation.component.html',
  styleUrls: ['./edit-organisation.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    LoaderComponent,
  ],
})
export class EditOrganisationImplComponent extends EditOrganisationComponent {
  @Input() id: string | any;

  override error = linkedSignal(() => this.organisationApiStore.error());
  override messages = linkedSignal(() => this.organisationApiStore.messages());
  override success = linkedSignal(() => this.organisationApiStore.success());
  organisation = this.organisationApiStore.data;

  constructor() {
    super();

    effect(() => {
      let organisation = this.organisationApiStore.data();
      this.editOrganisationForm.patchValue(organisation);
    });

    // Handle form control disabled state based on loading
    effect(() => {
      const isLoading = this.loading();
      if (isLoading) {
        this.editOrganisationForm.disable();
      } else {
        this.editOrganisationForm.enable();
      }
    });
  }

  override beforeOnInit(form: EditOrganisationVarsForm): EditOrganisationVarsForm {
    this.organisationApiStore.reset();

    this.route.queryParams.subscribe(params => {
      const id = params['id'];
      if (id) {
        this.id = id;
        this.organisationApiStore.findById({ id: this.id });
      }
    });


    return form;
  }

  doNgOnDestroy(): void { }

  override beforeEditOrganisationSave(form: any): void {
    this.organisationApiStore.save({ organisation: this.editOrganisationForm.value });
  }
}
