// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { Routes } from '@angular/router';

import { ClientRequestComponent } from '@views/client/client-request';

import { AuthenticationGuard } from '@app/auth/authentication.guard';

import { ClientRequestControllerImpl } from '@controllers/client/client-request-controller-impl';
import { ClientRequestApi } from '@services/bw/co/centralkyc/organisation/client/client-request-api';
import { EditClientRequestComponent } from './edit/edit-client-request';

export const routes: Routes = [
  {
      path: '',
      component: ClientRequestComponent,
      canActivate: [AuthenticationGuard],
      data: { title: 'Client Request' },
      providers: [
        ClientRequestControllerImpl,
        ClientRequestApi,
      ]
  },
  {
    path: 'edit',
    component: EditClientRequestComponent,
    canActivate: [AuthenticationGuard],
    data: { title: 'Edit Client Request' },
    providers: [
      ClientRequestControllerImpl,
      ClientRequestApi,
    ]
  },
  {
    path: 'edit/:id',
    component: EditClientRequestComponent,
    canActivate: [AuthenticationGuard],
    data: { title: 'Edit Client Request' },
    providers: [
      ClientRequestControllerImpl,
      ClientRequestApi,
    ]
  }

];

