// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchIndividualsComponent } from '@views/individual/search/search-individuals';
import { SearchIndividualsVarsForm } from '@views/individual/search/search-individuals';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';

@Component({
  selector: 'app-search-individuals',
  templateUrl: './search-individuals.html',
  styleUrls: ['./search-individuals.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class SearchIndividualsImplComponent extends SearchIndividualsComponent {

    constructor() {
        super();
    }
    doNgOnDestroy(): void {
    }

    individualsTableActionClicked(event: any): void {

    }
}
