// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.kyc;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import bw.co.centralkyc.AuditTracker;

import java.util.Collection;

import org.springframework.data.domain.Page;

@org.springframework.web.bind.annotation.RestController
public class KycRecordApiImpl implements KycRecordApi {

    private final KycRecordService kycRecordService;

    public KycRecordApiImpl(KycRecordService kycRecordService) {

        this.kycRecordService = kycRecordService;
    }

    @Override
    public ResponseEntity<KycRecordDTO> findById(String id) throws Exception {

        try {

            return ResponseEntity.ok(kycRecordService.findById(id));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> findByIdentityNo(String identityNo)
            throws Exception {

        try {

            return ResponseEntity.ok(kycRecordService.findByIdentityNo(identityNo));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> findByIndividual(String individualId)
            throws Exception {

        try {
            
            return ResponseEntity.ok(kycRecordService.findByIndividual(individualId));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> getAll() throws Exception {

        try {
            return ResponseEntity.ok(kycRecordService.getAll());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordDTO>> getAllPaged(Integer pageNumber, Integer pageSize)
            throws Exception {

        try {
            return ResponseEntity.ok(kycRecordService.getAll(pageNumber, pageSize));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordDTO>> pagedSearch(String criteria, Integer pageNumber,
            Integer pageSize) throws Exception {

        try {
            return ResponseEntity.ok(kycRecordService.search(criteria, pageNumber, pageSize));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(kycRecordService.remove(id));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> save(KycRecordDTO kycRecord) throws Exception {
        try {
            
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(kycRecord, authentication);

            return ResponseEntity.ok(kycRecordService.save(kycRecord));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> search(String criteria) throws Exception {
        try {
            
            return ResponseEntity.ok(kycRecordService.search(criteria));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
}