// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, computed, effect, inject, linkedSignal } from '@angular/core';
import { EditSettingsComponent } from '@app/view/settings/edit-settings.component';
import { EditSettingsVarsForm } from '@app/view/settings/edit-settings.component';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';
import { SettingsApiStore } from '@app/store/bw/co/centralkyc/settings/settings-api.store';
import { DocumentTypeApiStore } from '@app/store/bw/co/centralkyc/document/type/document-type-api.store';
import { DocumentTypeApi } from '@app/service/bw/co/centralkyc/document/type/document-type-api';
import { SettingsDTO } from '@app/model/bw/co/centralkyc/settings/settings-dto';
import { DocumentApi } from '@app/service/bw/co/centralkyc/document/document-api';
import { TargetEntity } from '@app/model/bw/co/centralkyc/target-entity';
import { SettingsApi } from '@app/service/bw/co/centralkyc/settings/settings-api';
import { DocumentTypePurpose } from '@app/model/bw/co/centralkyc/settings/document-type-purpose';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-edit-settings',
  templateUrl: './edit-settings.component.html',
  styleUrls: ['./edit-settings.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class EditSettingsImplComponent extends EditSettingsComponent {
  settingApiStore = inject(SettingsApiStore);
  settingApi = inject(SettingsApi);
  documentTypeApiStore = inject(DocumentTypeApiStore);
  documentTypeApi = inject(DocumentTypeApi);
  documentApi = inject(DocumentApi);

  override organisationDocumentsTableSignal = computed(() => this.settingApiStore?.data()?.organisationDocuments || []);
  override individualDocumentsTableSignal = computed(() => this.settingApiStore?.data()?.individualDocuments || []);
  override orgKycDocumentsTableSignal = computed(() => this.settingApiStore?.data()?.orgKycDocuments || []);
  override indKycDocumentsTableSignal = computed(() => this.settingApiStore?.data()?.indKycDocuments || []);

  override loading = linkedSignal(() => this.settingApiStore.loading());
  override error = linkedSignal(() => this.settingApiStore.error());
  override messages = linkedSignal(() => this.settingApiStore.messages());
  override success = linkedSignal(() => this.settingApiStore.success());

  settings: SettingsDTO = new SettingsDTO();

  constructor() {
    super();

    effect(() => {
      this.settings = this.settingApiStore.data();
      this.editSettingsForm.patchValue(this.settings);

      this.invoiceDocumentTypeFilteredList.set([this.settings.invoiceDocumentType]);
      this.invoiceTemplateTypeFilteredList.set([this.settings.invoiceTemplateType]);
      this.quotationDocumentTypeFilteredList.set([this.settings.quotationDocumentType]);
      this.quotationTemplateTypeFilteredList.set([this.settings.quotationTemplateType]);
      this.clientRequestFileTypeFilteredList.set([this.settings.clientRequestFileType]);
    });
  }

  override beforeOnInit(form: EditSettingsVarsForm): EditSettingsVarsForm {
    this.settingApiStore.reset();
    this.settingApiStore.getAll();

    this.organisationDocumentsTablePaged.set(false);
    this.individualDocumentsTablePaged.set(false);
    this.orgKycDocumentsTablePaged.set(false);
    this.indKycDocumentsTablePaged.set(false);

    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.settingApiStore.findById(params);
      }
    });
    return form;
  }

  doNgOnDestroy(): void {}

  private getSettings(value: any): SettingsDTO {
    let settings: SettingsDTO = {};
    settings.createdAt = value.createdAt;
    settings.createdBy = value.createdBy;
    settings.modifiedAt = value.modifiedAt;
    settings.modifiedBy = value.modifiedBy;
    settings.id = value.id;
    settings.kycDuration = value.kycDuration;
    settings.organisationDocuments = value.organisationDocuments || [];
    settings.individualDocuments = value.individualDocuments || [];
    settings.indKycDocuments = value.indKycDocuments || [];
    settings.orgKycDocuments = value.orgKycDocuments || [];
    settings.invoiceDocumentType = value.invoiceDocumentType;
    settings.clientRequestFileType = value.clientRequestFileType;
    settings.invoiceTemplateType = value.invoiceTemplateType;
    settings.invoiceTemplate = value.invoiceTemplate;
    settings.quotationDocumentType = value.quotationDocumentType;
    settings.quotationTemplateType = value.quotationTemplateType;
    settings.quotationTemplate = value.quotationTemplate;

    return settings;
  }

  override beforeEditSettingsSave(form: any): void {
    let val: any = this.editSettingsForm.value;
    let settings = this.getSettings(val);

    this.settingApiStore.save({ setttings: settings });
  }

  override filterSelectedOrgDocument(): void {
    const search = this.selectedOrgDocumentFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.selectedOrgDocumentFilteredList.set(data || []);
    });
  }

  override filterInvoiceDocumentType(): void {
    const search = this.invoiceDocumentTypeFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.invoiceDocumentTypeFilteredList.set(data || []);
    });
  }

  override filterClientRequestFileType(): void {
    const search = this.clientRequestFileTypeFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.clientRequestFileTypeFilteredList.set(data || []);
    });
  }

  override filterInvoiceTemplateType(): void {
    const search = this.invoiceTemplateTypeFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.invoiceTemplateTypeFilteredList.set(data || []);
    });
  }

  override filterQuotationDocumentType(): void {
    const search = this.quotationDocumentTypeFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.quotationDocumentTypeFilteredList.set(data || []);
    });
  }

  override filterQuotationTemplateType(): void {
    const search = this.quotationTemplateTypeFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.quotationTemplateTypeFilteredList.set(data || []);
    });
  }

  override filterSelectedKycOrgDocument(): void {
    const search = this.selectedKycOrgDocumentFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.selectedKycOrgDocumentFilteredList.set(data || []);
    });
  }

  override filterSelectedIndDocument(): void {
    const search = this.selectedIndDocumentFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.selectedIndDocumentFilteredList.set(data || []);
    });
  }

  override filterSelectedKycIndDocument(): void {
    const search = this.selectedKycIndDocumentFilterCtrl.value?.toLowerCase() || '';
    this.documentTypeApi.search(search).subscribe((data) => {
      this.selectedKycIndDocumentFilteredList.set(data || []);
    });
  }

  override onAddToIndDocumentsClick() {
    
    this.settingApiStore.attachDocumentType({
      documentTypeId: this.selectedIndDocumentControl.value.id,
      purpose: DocumentTypePurpose.INDIVIDUAL,
    });
    this.selectedIndDocumentControl.setValue(null);
  }

  override onAddToKycOrgDocumentsClick() {

    this.settingApiStore.attachDocumentType({
      documentTypeId: this.selectedKycOrgDocumentControl.value.id,
      purpose: DocumentTypePurpose.ORGANISATION_KYC,
    });
    this.selectedKycOrgDocumentControl.setValue(null);
  }

  override onAddToOrgDocumentsClick() {
    console.log(this.selectedOrgDocumentControl.value);
    
    this.settingApiStore.attachDocumentType({
      documentTypeId: this.selectedOrgDocumentControl.value.id,
      purpose: DocumentTypePurpose.ORGANISATION,
    });
    this.selectedOrgDocumentControl.setValue(null);
  }

  override onAddToKycIndDocumentsClick() {
    this.settingApiStore.attachDocumentType({
      documentTypeId: this.selectedKycIndDocumentControl.value.id,
      purpose: DocumentTypePurpose.INDIVIDUAL_KYC,
    });
    this.selectedKycIndDocumentControl.setValue(null);
  }

  attachInvoiceTemplate(): void {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept =
      'application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    input.onchange = (event: any) => {
      const file = event.target.files[0];
      if (file) {
        this.handleInvoiceTemplateUpload(file);
      }
    };
    input.click();
  }

  attachQuotationTemplate(): void {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept =
      'application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    input.onchange = (event: any) => {
      const file = event.target.files[0];
      if (file) {
        this.handleQuotationTemplateUpload(file);
      }
    };
    input.click();
  }

  private handleInvoiceTemplateUpload(file: File): void {
    // TODO: Implement invoice template upload logic
    console.log('Invoice template upload:', file.name);

    this.settingApiStore.uploadTemplate({ template: file, target: TargetEntity.INVOICE });
  }

  private handleQuotationTemplateUpload(file: File): void {
    // TODO: Implement quotation template upload logic
    console.log('Quotation template upload:', file.name);

    this.settingApiStore.uploadTemplate({ template: file, target: TargetEntity.QUOTATION });
  }

  downloadTemplate(target: TargetEntity): void {
    if (target === TargetEntity.INVOICE) {
    } else if (target === TargetEntity.QUOTATION) {
    }

    const docId =
      target === TargetEntity.INVOICE
        ? this.editSettingsForm.get('invoiceTemplate')?.value?.id
        : this.editSettingsForm.get('quotationTemplate')?.value?.id;

    if (!docId) {
      this.toaster.error('No template document available for download', 'Download Error');
      return;
    }

    let doc = target === TargetEntity.INVOICE ? this.settings.invoiceTemplate : this.settings.quotationTemplate;

    this.documentApi.downloadFile(doc?.id).subscribe({
      next: (res: any) => {
        const url = window.URL.createObjectURL(res);
        const a = document.createElement('a');
        a.href = url;

        // Optional: set a meaningful filename
        a.download = `${doc?.fileName}.pdf`; // or dynamically get filename from backend
        a.click();

        window.URL.revokeObjectURL(url); // clean up
      },
      error: (err: any) => {
        this.toaster.error(err.message || 'Failed to download file', 'Download Error');
      },
      complete: () => {
        // this.isDownloading.set('');
      },
    });
  }

  organisationDocumentsTableActionClicked(event: any): void {

    console.log(event)

    switch (event.action) {
      case 'settings-detach-org-documents':
        Swal.fire({
          title: 'Are you sure?',
          text: 'You are about to detach this document type from organisation documents. This action cannot be undone.',
          icon: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Yes',
          cancelButtonText: 'No',
        }).then((result) => {
          if (result.isConfirmed) {
            this.settingApiStore.detachDocumentType({
              documentTypeId: event.row.id,
              purpose: DocumentTypePurpose.ORGANISATION,
            });
            Swal.fire('Detached!', 'The document type has been detached from organisation documents.', 'success');
          }
        });

        break;
    }
  }

  individualDocumentsTableActionClicked(event: any): void {
    switch (event.action) {
      case 'settings-detach-individual-documents':
        // TODO: Implement the action

        Swal.fire({
          title: 'Are you sure?',
          text: 'You are about to detach this document type from individual documents. This action cannot be undone.',
          icon: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Yes',
          cancelButtonText: 'No',
        }).then((result) => {
          if (result.isConfirmed) {

            this.settingApiStore.detachDocumentType({
              documentTypeId: event.row.id,
              purpose: DocumentTypePurpose.INDIVIDUAL,
            });
            Swal.fire('Detached!', 'The document type has been detached from individual documents.', 'success');
          }
        });

        break;
    }
  }

  orgKycDocumentsTableActionClicked(event: any): void {
    switch (event.action) {
      case 'settings-detach-org-kyc-documents':
        // TODO: Implement the action
        Swal.fire({
          title: 'Are you sure?',
          text: 'You are about to detach this document type from organisation KYC documents. This action cannot be undone.',
          icon: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Yes',
          cancelButtonText: 'No',
        }).then((result) => {
          if (result.isConfirmed) {

            this.settingApiStore.detachDocumentType({
              documentTypeId: event.row.id,
              purpose: DocumentTypePurpose.ORGANISATION_KYC,
            });
            Swal.fire('Detached!', 'The document type has been detached from organisation KYC documents.', 'success');
          }
        });
        break;
    }
  }

  indKycDocumentsTableActionClicked(event: any): void {
      let form: any = {};
      let queryParams: any = {};
      let params: any = {};
  
      switch (event.action) {
        case 'settings-detach-ind-kyc-documents':
          // TODO: Implement the action
          
          Swal.fire({
            title: 'Are you sure?',
            text: 'You are about to detach this document type from individual KYC documents. This action cannot be undone.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes',
            cancelButtonText: 'No',
          }).then((result) => {
            if (result.isConfirmed) {
  
              this.settingApiStore.detachDocumentType({
                documentTypeId: event.row.id,
                purpose: DocumentTypePurpose.INDIVIDUAL_KYC,
              });
              Swal.fire('Detached!', 'The document type has been detached from individual KYC documents.', 'success');
            }
          });

          break;
      }
    }
}
