// Generated by andromda-angular cartridge (view\view.component.ts.vsl) DO NOT EDIT
import {
  Component,
  OnInit,
  effect,
  inject,
  ViewChild,
  Input,
  Output,
  EventEmitter,
  AfterViewInit,
  signal,
  Signal,
  linkedSignal,
  WritableSignal,
  OnDestroy,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import {
  FormGroup,
  FormControl,
  FormArray,
  FormBuilder,
  ReactiveFormsModule,
  Validators
} from '@angular/forms';
import { formatDate } from '@angular/common';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { Store, select } from '@ngrx/store';
import { Observable, of, Subscription } from 'rxjs';
import { SearchObject } from '@app/model/search-object';
import { MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';
import { MatChipInputEvent } from '@angular/material/chips';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { TableComponent } from '@app/components/table/table.component';
import { SettingsApiStore } from '@app/store/bw/co/centralkyc/settings/settings-api.store';
import { ColumnModel } from '@app/model/column.model';
import { ActionTemplate } from '@app/model/action-template';

import { DocumentTypeDTO } from '@app/model/bw/co/centralkyc/document/type/document-type-dto';
import { TargetEntity } from '@app/model/bw/co/centralkyc/target-entity';
import { SettingsApi } from '@app/service/bw/co/centralkyc/settings/settings-api';
import { SettingsDTO } from '@app/model/bw/co/centralkyc/settings/settings-dto';
import { DocumentDTO } from '@app/model/bw/co/centralkyc/document/document-dto';
import { SettingsControllerImpl } from '@app/controller/settings/settings-controller.impl';
import { ToastrService } from 'ngx-toastr';
import { Page } from '@app/model/page.model';

export class EditSettingsVarsForm {
  id?: string | any;
  createdAt?: Date | any;
  createdBy?: string | any;
  modifiedAt?: Date | any;
  modifiedBy?: string | any;
  kycDuration?: number | any;
  selectedOrgDocument?: DocumentTypeDTO | any;
  selectedKycOrgDocument?: DocumentTypeDTO | any;
  selectedIndDocument?: DocumentTypeDTO | any;
  selectedKycIndDocument?: DocumentTypeDTO | any;
  invoiceDocumentType?: DocumentTypeDTO | any;
  invoiceTemplateType?: DocumentTypeDTO | any;
  invoiceTemplate?: DocumentDTO | any;
  quotationDocumentType?: DocumentTypeDTO | any;
  quotationTemplateType?: DocumentTypeDTO | any;
  quotationTemplate?: DocumentDTO | any;
}

@Component({
  selector: 'app-edit-settings-base',
  template: ''
})
export abstract class EditSettingsComponent implements OnInit, AfterViewInit, OnDestroy {

  separatorKeysCodes: number[] = [ENTER, COMMA];
  @Input() editSettingsVarsForm: EditSettingsVarsForm = {};

  editSettingsForm: FormGroup = new FormGroup({});
  hide: boolean = false;
  protected route: ActivatedRoute = inject(ActivatedRoute);
  protected router: Router = inject(Router);
  protected formBuilder: FormBuilder = inject(FormBuilder);
  protected useCaseScope: UseCaseScope = inject(UseCaseScope);
  dialog: MatDialog = inject(MatDialog);
  toaster: ToastrService = inject(ToastrService);
  settingsController: SettingsControllerImpl = inject(SettingsControllerImpl);
  readonly settingsApiStore = inject(SettingsApiStore);
  selectedOrgDocumentFilterCtrl: FormControl = new FormControl();

  selectedOrgDocumentCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterSelectedOrgDocument() { }

  selectedOrgDocumentBackingList: DocumentTypeDTO[] = [];
  selectedOrgDocumentFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  selectedOrgDocumentChipControl: FormControl = new FormControl([]);

  selectedOrgDocumentDisplays: string[] = [
    'name',
  ];

  @ViewChild('organisationDocumentsTable') organisationDocumentsTable?: TableComponent<DocumentTypeDTO>;
  organisationDocumentsTableSignal: Signal<any | DocumentTypeDTO | Page<DocumentTypeDTO>> = signal(null);
  organisationDocumentsTablePaged: WritableSignal<boolean> = linkedSignal(() => true);

  organisationDocumentsTableColumnsActions: ActionTemplate[] = [
  ];

  showOrganisationDocumentsActions = false;

  selectedKycOrgDocumentFilterCtrl: FormControl = new FormControl();

  selectedKycOrgDocumentCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterSelectedKycOrgDocument() { }

  selectedKycOrgDocumentBackingList: DocumentTypeDTO[] = [];
  selectedKycOrgDocumentFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  selectedKycOrgDocumentChipControl: FormControl = new FormControl([]);

  selectedKycOrgDocumentDisplays: string[] = [
    'name',
  ];

  @ViewChild('orgKycDocumentsTable') orgKycDocumentsTable?: TableComponent<DocumentTypeDTO>;
  orgKycDocumentsTableSignal: Signal<any | DocumentTypeDTO | Page<DocumentTypeDTO>> = signal(null);
  orgKycDocumentsTablePaged: WritableSignal<boolean> = linkedSignal(() => true);

  orgKycDocumentsTableColumnsActions: ActionTemplate[] = [
  ];

  showOrgKycDocumentsActions = false;

  selectedIndDocumentFilterCtrl: FormControl = new FormControl();

  selectedIndDocumentCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterSelectedIndDocument() { }

  selectedIndDocumentBackingList: DocumentTypeDTO[] = [];
  selectedIndDocumentFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  selectedIndDocumentChipControl: FormControl = new FormControl([]);

  selectedIndDocumentDisplays: string[] = [
    'name',
  ];

  @ViewChild('individualDocumentsTable') individualDocumentsTable?: TableComponent<DocumentTypeDTO>;
  individualDocumentsTableSignal: Signal<any | DocumentTypeDTO | Page<DocumentTypeDTO>> = signal(null);
  individualDocumentsTablePaged: WritableSignal<boolean> = linkedSignal(() => true);

  individualDocumentsTableColumnsActions: ActionTemplate[] = [
  ];

  showIndividualDocumentsActions = false;

  selectedKycIndDocumentFilterCtrl: FormControl = new FormControl();

  selectedKycIndDocumentCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterSelectedKycIndDocument() { }

  selectedKycIndDocumentBackingList: DocumentTypeDTO[] = [];
  selectedKycIndDocumentFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  selectedKycIndDocumentChipControl: FormControl = new FormControl([]);

  selectedKycIndDocumentDisplays: string[] = [
    'name',
  ];

  @ViewChild('indKycDocumentsTable') indKycDocumentsTable?: TableComponent<DocumentTypeDTO>;
  indKycDocumentsTableSignal: Signal<any | DocumentTypeDTO | Page<DocumentTypeDTO>> = signal(null);
  indKycDocumentsTablePaged: WritableSignal<boolean> = linkedSignal(() => true);

  documentsTableColumns: ColumnModel[] = [
    new ColumnModel(
      'code',
      'code',
      false,
    ),
    new ColumnModel(
      'name',
      'name',
      false,
    ),
  ];

  indKycDocumentsTableColumnsActions: ActionTemplate[] = [
  ];

  showIndKycDocumentsActions = false;

  invoiceDocumentTypeFilterCtrl: FormControl = new FormControl();

  invoiceDocumentTypeCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterInvoiceDocumentType() { }

  invoiceDocumentTypeBackingList: DocumentTypeDTO[] = [];
  invoiceDocumentTypeFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  invoiceDocumentTypeChipControl: FormControl = new FormControl([]);

  invoiceDocumentTypeDisplays: string[] = [
    'name',
  ];

  invoiceTemplateTypeFilterCtrl: FormControl = new FormControl();

  invoiceTemplateTypeCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterInvoiceTemplateType() { }

  invoiceTemplateTypeBackingList: DocumentTypeDTO[] = [];
  invoiceTemplateTypeFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  invoiceTemplateTypeChipControl: FormControl = new FormControl([]);

  invoiceTemplateTypeDisplays: string[] = [
    'name',
  ];

  quotationDocumentTypeFilterCtrl: FormControl = new FormControl();

  quotationDocumentTypeCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterQuotationDocumentType() { }

  quotationDocumentTypeBackingList: DocumentTypeDTO[] = [];
  quotationDocumentTypeFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  quotationDocumentTypeChipControl: FormControl = new FormControl([]);

  quotationDocumentTypeDisplays: string[] = [
    'name',
  ];

  quotationTemplateTypeFilterCtrl: FormControl = new FormControl();

  quotationTemplateTypeCompare(o1: DocumentTypeDTO | any, o2: DocumentTypeDTO | any) {
    return o1 && o2 && o1.id === o2.id;
  }

  filterQuotationTemplateType() { }

  quotationTemplateTypeBackingList: DocumentTypeDTO[] = [];
  quotationTemplateTypeFilteredList: WritableSignal<DocumentTypeDTO[] | any[]> = linkedSignal(() => []);
  quotationTemplateTypeChipControl: FormControl = new FormControl([]);

  quotationTemplateTypeDisplays: string[] = [
    'name',
  ];

  TargetEntityT: any = TargetEntity;
  TargetEntityOptions = Object.keys(this.TargetEntityT);
  loaderMessage: Signal<string> = signal('');
  messages: Signal<string[]> = signal([]);
  success: Signal<boolean> = signal(false);
  loading: Signal<boolean> = signal(false);
  error: Signal<boolean> = signal(false);
  selected: Signal<any> = signal(null);

  editSettingsFormValueSubscription?: Subscription;

  constructor() {


    effect(() => {
      let messages = this.messages();

      if (this.success() && !this.loading()) {
        this.toaster.success(messages[0]);
      }

      if (this.error() && !this.loading()) {
        this.toaster.error(messages[0]);
      }
    })
  }

  abstract beforeOnInit(form: EditSettingsVarsForm): EditSettingsVarsForm;

  ngOnInit() {
    let form: EditSettingsVarsForm = this.beforeOnInit(new EditSettingsVarsForm);
    this.editSettingsForm = this.newForm(form);

    this.editSettingsFormValueSubscription = this.editSettingsForm.valueChanges.subscribe(
      (change: any) => {
        this.handleFormChanges(change);
      }
    );

    this.afterOnInit();
  }

  handleFormChanges(change: any): void {

  }

  editSettingsFormReset() {

    this.editSettingsForm.reset()
    this.editSettingsForm.markAsPristine();

    if (this.router.url.substring(0, this.router.url.indexOf('?'))) {
      this.router.navigate([this.router.url.substring(0, this.router.url.indexOf('?'))]);
    } else {
      this.router.navigate([this.router.url]);
    }
  }

  afterOnInit(): void { }

  doNgAfterViewInit(): void { }

  ngAfterViewInit() {
    this.doNgAfterViewInit();
    this.settingsController.resetUseCaseScope();
  }

  newForm(editSettingsVarsForm: EditSettingsVarsForm): FormGroup {
    return this.formBuilder.group({
      id: [{ value: this.editSettingsVarsForm.id, disabled: false }],
      createdAt: [{ value: this.editSettingsVarsForm.createdAt, disabled: false }],
      createdBy: [{ value: this.editSettingsVarsForm.createdBy, disabled: false }],
      modifiedAt: [{ value: this.editSettingsVarsForm.modifiedAt, disabled: false }],
      modifiedBy: [{ value: this.editSettingsVarsForm.modifiedBy, disabled: false }],
      kycDuration: [{ value: this.editSettingsVarsForm.kycDuration, disabled: false }, [Validators.required,]],
      selectedOrgDocument: [{ value: this.editSettingsVarsForm.selectedOrgDocument, disabled: false }],
      selectedKycOrgDocument: [{ value: this.editSettingsVarsForm.selectedKycOrgDocument, disabled: false }],
      selectedIndDocument: [{ value: this.editSettingsVarsForm.selectedIndDocument, disabled: false }],
      selectedKycIndDocument: [{ value: this.editSettingsVarsForm.selectedKycIndDocument, disabled: false }],
      invoiceDocumentType: [{ value: this.editSettingsVarsForm.invoiceDocumentType, disabled: false }, [Validators.required,]],
      invoiceTemplateType: [{ value: this.editSettingsVarsForm.invoiceTemplateType, disabled: false }, [Validators.required,]],
      invoiceTemplate: this.createDocumentDTOGroup(this.editSettingsVarsForm.invoiceTemplate),
      quotationDocumentType: [{ value: this.editSettingsVarsForm.quotationDocumentType, disabled: false }, [Validators.required,]],
      quotationTemplateType: [{ value: this.editSettingsVarsForm.quotationTemplateType, disabled: false }, [Validators.required,]],
      quotationTemplate: this.createDocumentDTOGroup(this.editSettingsVarsForm.quotationTemplate),

    });
  }

  abstract doNgOnDestroy(): void;

  ngOnDestroy() {
    this.doNgOnDestroy();
    if (this.editSettingsFormValueSubscription) {
      this.editSettingsFormValueSubscription.unsubscribe();
    }
  }

  /**
   * This method may be overwritten
   */
  beforeEditSettingsSave(form: any): void { }

  /**
   * This method may be overwritten
   */
  afterEditSettingsSave(form: any): void { }

  /**
   * This method may be overwritten
   */
  get editSettingsSaveSettings(): SettingsDTO {
    return {} as SettingsDTO;
  }

  editSettingsSave(): void {

    let form: any = {
      settings: this.editSettingsSaveSettings,
    };

    this.beforeEditSettingsSave(form);

    this.settingsController.editSettingsSave(form.settings);
    this.afterEditSettingsSave(form);
  }

  get editSettingsVarsFormControl(): FormGroup {
    return this.getGroupControl('editSettingsVarsForm');
  }

  get idControl(): FormControl {
    return this.editSettingsForm?.get('id') as FormControl;
  }

  get createdAtControl(): FormControl {
    return this.editSettingsForm?.get('createdAt') as FormControl;
  }

  get createdByControl(): FormControl {
    return this.editSettingsForm?.get('createdBy') as FormControl;
  }

  get modifiedAtControl(): FormControl {
    return this.editSettingsForm?.get('modifiedAt') as FormControl;
  }

  get modifiedByControl(): FormControl {
    return this.editSettingsForm?.get('modifiedBy') as FormControl;
  }

  get kycDurationControl(): FormControl {
    return this.editSettingsForm?.get('kycDuration') as FormControl;
  }

  createDocumentTypeDTOGroup(value?: DocumentTypeDTO): FormGroup {
    return this.formBuilder.group({
      code: [value?.code],
      name: [value?.name],
      description: [value?.description],
      id: [value?.id],
      createdBy: [value?.createdBy],
      createdAt: [value?.createdAt],
      modifiedBy: [value?.modifiedBy],
      modifiedAt: [value?.modifiedAt],
    });
  }

  createDocumentTypeDTOArray(values?: DocumentTypeDTO[]): FormArray {
    if (values) {
      let formArray: FormArray = this.formBuilder.array([]);
      values?.forEach(value => formArray.push(this.createDocumentTypeDTOGroup(value)))

      return formArray;
    } else {
      return new FormArray([] as any);
    }
  }

  get selectedOrgDocumentControl(): FormControl {
    return this.editSettingsForm?.get('selectedOrgDocument') as FormControl;
  }

  selectedOrgDocumentAddDialog() { }

  selectedOrgDocumentClear() { }

  selectedOrgDocumentSelected(event: MatCheckboxChange, row: number) { }

  selectedOrgDocumentSearch() { }

  addSelectedSelectedOrgDocument() { }

  get selectedKycOrgDocumentControl(): FormControl {
    return this.editSettingsForm?.get('selectedKycOrgDocument') as FormControl;
  }

  selectedKycOrgDocumentAddDialog() { }

  selectedKycOrgDocumentClear() { }

  selectedKycOrgDocumentSelected(event: MatCheckboxChange, row: number) { }

  selectedKycOrgDocumentSearch() { }

  addSelectedSelectedKycOrgDocument() { }

  get selectedIndDocumentControl(): FormControl {
    return this.editSettingsForm?.get('selectedIndDocument') as FormControl;
  }

  selectedIndDocumentAddDialog() { }

  selectedIndDocumentClear() { }

  selectedIndDocumentSelected(event: MatCheckboxChange, row: number) { }

  selectedIndDocumentSearch() { }

  addSelectedSelectedIndDocument() { }

  get selectedKycIndDocumentControl(): FormControl {
    return this.editSettingsForm?.get('selectedKycIndDocument') as FormControl;
  }

  selectedKycIndDocumentAddDialog() { }

  selectedKycIndDocumentClear() { }

  selectedKycIndDocumentSelected(event: MatCheckboxChange, row: number) { }

  selectedKycIndDocumentSearch() { }

  addSelectedSelectedKycIndDocument() { }

  get invoiceDocumentTypeControl(): FormControl {
    return this.editSettingsForm?.get('invoiceDocumentType') as FormControl;
  }

  invoiceDocumentTypeAddDialog() { }

  invoiceDocumentTypeClear() { }

  invoiceDocumentTypeSelected(event: MatCheckboxChange, row: number) { }

  invoiceDocumentTypeSearch() { }

  addSelectedInvoiceDocumentType() { }

  get invoiceTemplateTypeControl(): FormControl {
    return this.editSettingsForm?.get('invoiceTemplateType') as FormControl;
  }

  invoiceTemplateTypeAddDialog() { }

  invoiceTemplateTypeClear() { }

  invoiceTemplateTypeSelected(event: MatCheckboxChange, row: number) { }

  invoiceTemplateTypeSearch() { }

  addSelectedInvoiceTemplateType() { }



  createDocumentDTOGroup(value?: DocumentDTO): FormGroup {
    return this.formBuilder.group({
      target: [value?.target],
      documentTypeId: [value?.documentTypeId],
      documentType: [value?.documentType],
      url: [value?.url],
      targetId: [value?.targetId],
      metadata: [value?.metadata],
      fileName: [value?.fileName],
      id: [value?.id],
      createdBy: [value?.createdBy],
      createdAt: [value?.createdAt],
      modifiedBy: [value?.modifiedBy],
      modifiedAt: [value?.modifiedAt],
    });
  }

  createDocumentDTOArray(values?: DocumentDTO[]): FormArray {
    if (values) {
      let formArray: FormArray = this.formBuilder.array([]);
      values?.forEach(value => formArray.push(this.createDocumentDTOGroup(value)))

      return formArray;
    } else {
      return new FormArray([] as any);
    }
  }

  get invoiceTemplateControl(): FormGroup {
    return this.editSettingsForm?.get('invoiceTemplate') as FormGroup;
  }

  invoiceTemplateAddDialog() { }

  invoiceTemplateClear() { }

  invoiceTemplateSelected(event: MatCheckboxChange, row: number) { }

  invoiceTemplateSearch() { }

  addSelectedInvoiceTemplate() { }

  get invoiceTemplateTargetControl(): FormGroup {
    return this.invoiceTemplateControl?.get('target') as FormGroup;
  }

  get invoiceTemplateDocumentTypeIdControl(): FormControl {
    return this.invoiceTemplateControl?.get('documentTypeId') as FormControl;
  }

  get invoiceTemplateDocumentTypeControl(): FormControl {
    return this.invoiceTemplateControl?.get('documentType') as FormControl;
  }

  get invoiceTemplateUrlControl(): FormControl {
    return this.invoiceTemplateControl?.get('url') as FormControl;
  }

  get invoiceTemplateTargetIdControl(): FormControl {
    return this.invoiceTemplateControl?.get('targetId') as FormControl;
  }

  get invoiceTemplateMetadataControl(): FormControl {
    return this.invoiceTemplateControl?.get('metadata') as FormControl;
  }

  get invoiceTemplateFileNameControl(): FormControl {
    return this.invoiceTemplateControl?.get('fileName') as FormControl;
  }

  get quotationDocumentTypeControl(): FormControl {
    return this.editSettingsForm?.get('quotationDocumentType') as FormControl;
  }

  quotationDocumentTypeAddDialog() { }

  quotationDocumentTypeClear() { }

  quotationDocumentTypeSelected(event: MatCheckboxChange, row: number) { }

  quotationDocumentTypeSearch() { }

  addSelectedQuotationDocumentType() { }

  get quotationTemplateTypeControl(): FormControl {
    return this.editSettingsForm?.get('quotationTemplateType') as FormControl;
  }

  quotationTemplateTypeAddDialog() { }

  quotationTemplateTypeClear() { }

  quotationTemplateTypeSelected(event: MatCheckboxChange, row: number) { }

  quotationTemplateTypeSearch() { }

  addSelectedQuotationTemplateType() { }

  get quotationTemplateControl(): FormGroup {
    return this.editSettingsForm?.get('quotationTemplate') as FormGroup;
  }

  quotationTemplateAddDialog() { }

  quotationTemplateClear() { }

  quotationTemplateSelected(event: MatCheckboxChange, row: number) { }

  quotationTemplateSearch() { }

  addSelectedQuotationTemplate() { }

  get quotationTemplateTargetControl(): FormGroup {
    return this.quotationTemplateControl?.get('target') as FormGroup;
  }

  get quotationTemplateDocumentTypeIdControl(): FormControl {
    return this.quotationTemplateControl?.get('documentTypeId') as FormControl;
  }

  get quotationTemplateDocumentTypeControl(): FormControl {
    return this.quotationTemplateControl?.get('documentType') as FormControl;
  }

  get quotationTemplateUrlControl(): FormControl {
    return this.quotationTemplateControl?.get('url') as FormControl;
  }

  get quotationTemplateTargetIdControl(): FormControl {
    return this.quotationTemplateControl?.get('targetId') as FormControl;
  }

  get quotationTemplateMetadataControl(): FormControl {
    return this.quotationTemplateControl?.get('metadata') as FormControl;
  }

  get quotationTemplateFileNameControl(): FormControl {
    return this.quotationTemplateControl?.get('fileName') as FormControl;
  }

  getItemControl(name: string): FormControl {
    return this.editSettingsForm.get(name) as FormControl;
  }

  getGroupControl(name: string): FormGroup {
    return this.editSettingsForm.get(name) as FormGroup;
  }

  getArrayControl(name: string): FormArray {
    return this.editSettingsForm.get(name) as FormArray;
  }

  setEditSettingsFormValue(form: any) {
    if (form.id) {
      this.editSettingsForm?.get('id')?.setValue(form.id);
    }
    if (form.createdAt) {
      this.editSettingsForm?.get('createdAt')?.setValue(form.createdAt);
    }
    if (form.createdBy) {
      this.editSettingsForm?.get('createdBy')?.setValue(form.createdBy);
    }
    if (form.modifiedAt) {
      this.editSettingsForm?.get('modifiedAt')?.setValue(form.modifiedAt);
    }
    if (form.modifiedBy) {
      this.editSettingsForm?.get('modifiedBy')?.setValue(form.modifiedBy);
    }
    if (form.kycDuration) {
      this.editSettingsForm?.get('kycDuration')?.setValue(form.kycDuration);
    }
  }


  onAddToOrgDocumentsClick() { }

  onAddToKycOrgDocumentsClick() { }

  onAddToIndDocumentsClick() { }

  onAddToKycIndDocumentsClick() { }

}
