// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.subscription;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class KycSubscriptionApiImpl extends KycSubscriptionApiBase {
    
    public KycSubscriptionApiImpl(
        KycSubscriptionService kycSubscriptionService    ) {
        
        super(
            kycSubscriptionService        );
    }



    @Override
    public ResponseEntity<KycSubscriptionDTO> handleFindById(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<KycSubscriptionDTO>> handleGetAll() throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<KycSubscriptionDTO>> handleGetAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<KycSubscriptionDTO>> handlePagedSearch(String criteria, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> handleRemove(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<KycSubscriptionDTO> handleSave(KycSubscriptionDTO subscription) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<KycSubscriptionDTO>> handleSearch(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
}