// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditDocumentTypeComponent } from '@views/document/type/edit-document-type';
import { EditDocumentTypeVarsForm } from '@views/document/type/edit-document-type';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';

@Component({
  selector: 'app-edit-document-type',
  templateUrl: './edit-document-type.html',
  styleUrls: ['./edit-document-type.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class EditDocumentTypeImplComponent extends EditDocumentTypeComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditDocumentTypeVarsForm): EditDocumentTypeVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}