// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchDocumentTypesComponent } from '@views/document/type/search-document-types';
import { SearchDocumentTypesVarsForm } from '@views/document/type/search-document-types';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';

@Component({
  selector: 'app-search-document-types',
  templateUrl: './search-document-types.html',
  styleUrls: ['./search-document-types.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class SearchDocumentTypesImplComponent extends SearchDocumentTypesComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchDocumentTypesVarsForm): SearchDocumentTypesVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}