// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.organisation;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.keycloak.KeycloakOrganisationService;
import bw.co.centralkyc.organisation.client.ClientRequestDTO;

@org.springframework.web.bind.annotation.RestController
public class OrganisationApiImpl implements OrganisationApi {

    private final KeycloakOrganisationService orgService;
    private final OrganisationService organisationService;

    public OrganisationApiImpl(OrganisationService organisationService, KeycloakOrganisationService orgService) {

        this.orgService = orgService;
        this.organisationService = organisationService;
    }

    @Override
    public ResponseEntity<OrganisationDTO> findById(String id) {
        try {
            return ResponseEntity.ok(orgService.findById(id));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<OrganisationListDTO>> getAll() {
        try {
            return ResponseEntity.ok(organisationService.getAll());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<OrganisationListDTO>> getAllPaged(Integer pageNumber,
            Integer pageSize) {
        try {
            return ResponseEntity.ok(organisationService.getAll(pageNumber, pageSize));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Page<OrganisationListDTO>> pagedSearch(
            SearchObject<OrganisationSearchCriteria> criteria) {
        try {

            Page<OrganisationListDTO> results = orgService.search(criteria);

            updateOrganisationsDetails(results.getContent());

            return ResponseEntity.ok(results);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Boolean> remove(String id) {
        try {
            return ResponseEntity.ok(orgService.remove(id));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    private void updateOrganisationsDetails(Collection<OrganisationListDTO> orgs) {
        for (OrganisationListDTO org : orgs) {
            
            OrganisationDTO orgDetails = orgService.findById(org.getId());
            if(orgDetails != null) {
                org.contactEmailAddress = orgDetails.getContactEmailAddress();
                org.registrationNo = orgDetails.getRegistrationNo();
            }

        }
    }   

    @Override
    public ResponseEntity<OrganisationDTO> save(OrganisationDTO organisation) {
        try {
            
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(organisation, authentication);

            return ResponseEntity.ok(orgService.createOrganisation(organisation));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<OrganisationListDTO>> search(
            SearchObject<OrganisationSearchCriteria> criteria) {
        try {

            Set<PropertySearchOrder> sortings = new HashSet<>();

            if (criteria.getSortings() != null) {
                sortings.addAll(sortings);
            }
            
            Collection<OrganisationListDTO> results = orgService.search(
                    criteria.getCriteria());

            updateOrganisationsDetails(results);
            return ResponseEntity.ok(results);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }
}