// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::kyc::KycComplianceStatus
 */
export enum KycComplianceStatus {
    /** TODO: Model Documentation for Enumeration Literal CURRENT value "CURRENT" */
    CURRENT = "CURRENT",
    /** TODO: Model Documentation for Enumeration Literal EXPIRED value "EXPIRED" */
    EXPIRED = "EXPIRED",
    /** TODO: Model Documentation for Enumeration Literal ABSENT value "ABSENT" */
    ABSENT = "ABSENT",
    /** TODO: Model Documentation for Enumeration Literal INCOMPLETE value "INCOMPLETE" */
    INCOMPLETE = "INCOMPLETE"
}
