// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycRecordDTO } from '@app/model/bw/co/centralkyc/individual/kyc/kyc-record-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';
import { RestApiResponse } from '@app/model/rest-api-response.model';

@Injectable({
  providedIn: 'root'
})
export class KycRecordApi {
    
    protected path = '/kyc';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<RestApiResponse<KycRecordDTO | any>> {

        return this.http.get<RestApiResponse<KycRecordDTO | any>>(`${this.path}/${id}`);
    }

    public findByIdentityNo(identityNo: string | any ): Observable<RestApiResponse<KycRecordDTO[] | any[]>> {

        return this.http.get<RestApiResponse<KycRecordDTO[] | any[]>>(`${this.path}/by-identity/${identityNo}`);
    }

    public findByIndividual(individualId: string | any ): Observable<RestApiResponse<KycRecordDTO[] | any[]>> {

        return this.http.get<RestApiResponse<KycRecordDTO[] | any[]>>(`${this.path}/by-individual/${individualId}`);
    }

    public getAll(): Observable<RestApiResponse<KycRecordDTO[] | any[]>> {

        return this.http.get<RestApiResponse<KycRecordDTO[] | any[]>>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<RestApiResponse<Page<KycRecordDTO> | any>> {

        return this.http.get<RestApiResponse<Page<KycRecordDTO> | any>>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: string | any , pageNumber: number | any , pageSize: number | any ): Observable<RestApiResponse<Page<KycRecordDTO> | any>> {

        return this.http.get<RestApiResponse<Page<KycRecordDTO> | any>>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<RestApiResponse<boolean | any>> {

        return this.http.delete<RestApiResponse<boolean | any>>(`${this.path}/${id}`);
    }

    public save(kycRecord: KycRecordDTO | any ): Observable<RestApiResponse<KycRecordDTO | any>> {

        return this.http.post<RestApiResponse<KycRecordDTO | any>>(`${this.path}`, kycRecord);
    }

    public search(criteria: string | any ): Observable<RestApiResponse<KycRecordDTO[] | any[]>> {

        return this.http.get<RestApiResponse<KycRecordDTO[] | any[]>>(`${this.path}/search?criteria=${criteria}`);
    }

}
