// license-header angular merge-point
//
/**
 * @author Generated by app-routing.module.ts.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * MODEL CLASS:  $validationName
 */
import { Routes } from '@angular/router';
import { Shell } from '@app/shell/shell';
import { UseCaseScope } from './utils/use-case-scope';

export const routes: Routes = [
  Shell.childRoutes([
    {
      path: '',
      data: { title: 'Home' },
      loadComponent: () => import('./views/home/home').then((c) => c.Home),
    },
    {
      path: 'about',
      data: { title: 'About' },
      loadComponent: () => import('./views/about/about').then((c) => c.About),
    },
    {
      path: 'organisation', 
      loadChildren: () => import('@views/organisation/organisation.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'settings', 
      loadChildren: () => import('@views/settings/settings.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'document/type', 
      loadChildren: () => import('@views/document/type/document-type.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'individual', 
      loadChildren: () => import('@views/individual/individual.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'user', 
      loadChildren: () => import('@views/user/user.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'subscription', 
      loadChildren: () => import('@views/subscription/subcription.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'invoice', 
      loadChildren: () => import('@views/invoice/invoice.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'kyc', 
      loadChildren: () => import('@views/kyc/kyc-record.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'client-request', 
      loadChildren: () => import('@views/client/client-request.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
  ]),
  // Fallback when no prior route is matched
  { 
    path: '**', redirectTo: '', pathMatch: 'full' 
  },
];
