// license-header angular merge-point
//
/**
 * @author Generated by enum.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * TEMPLATE:     enumeration.vsl in andromda-angular-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.centralkyc::individual::MaritalStatus
 */
export enum MaritalStatus {
    /** TODO: Model Documentation for Enumeration Literal SINGLE value "SINGLE" */
    SINGLE = "SINGLE",
    /** TODO: Model Documentation for Enumeration Literal MARRIED value "MARRIED" */
    MARRIED = "MARRIED",
    /** TODO: Model Documentation for Enumeration Literal DIVORCED value "DIVORCED" */
    DIVORCED = "DIVORCED",
    /** TODO: Model Documentation for Enumeration Literal WIDOWED value "WIDOWED" */
    WIDOWED = "WIDOWED",
    /** TODO: Model Documentation for Enumeration Literal OTHER value "OTHER" */
    OTHER = "OTHER"
}
