// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.settings;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        SettingsMapper.class    }
)
public interface SalaryRangeMapper {
    
    /**
     * Converts this entity to an object of type {@link SalaryRangeDTO}.
     * @param entity
     * @return SalaryRangeDTO
     */
    SalaryRangeDTO toSalaryRangeDTO(SalaryRange entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SalaryRangeDTO}.
     * @param entities
     * @return Collection<SalaryRangeDTO>     */
    List<SalaryRangeDTO> toSalaryRangeDTOCollection(Collection<SalaryRange> entities);

    /**
     * Converts an instance of type {@link SalaryRangeDTO} to this DAO's entity.
     * @param salaryRangeDTO
     * @return SalaryRange
     */
    SalaryRange salaryRangeDTOToEntity(SalaryRangeDTO salaryRangeDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateSalaryRangeFromSalaryRangeDTO(SalaryRangeDTO salaryRangeDTO, @MappingTarget SalaryRange entity);

}