// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.settings;

import bw.co.centralkyc.document.DocumentMapper;
import bw.co.centralkyc.document.type.DocumentTypeMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        DocumentTypeMapper.class,
        DocumentMapper.class,
        SalaryRangeMapper.class    }
)
public interface SettingsMapper {
    
    /**
     * Converts this entity to an object of type {@link SettingsDTO}.
     * @param entity
     * @return SettingsDTO
     */
    SettingsDTO toSettingsDTO(Settings entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SettingsDTO}.
     * @param entities
     * @return Collection<SettingsDTO>     */
    List<SettingsDTO> toSettingsDTOCollection(Collection<Settings> entities);

    /**
     * Converts an instance of type {@link SettingsDTO} to this DAO's entity.
     * @param settingsDTO
     * @return Settings
     */
    Settings settingsDTOToEntity(SettingsDTO settingsDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateSettingsFromSettingsDTO(SettingsDTO settingsDTO, @MappingTarget Settings entity);

}