// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycInvoiceDTO } from '@app/model/bw/co/centralkyc/invoice/kyc-invoice-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class KycInvoiceApi {

    protected path = '/invoice';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<KycInvoiceDTO> {

        return this.http.get<KycInvoiceDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<KycInvoiceDTO[]> {

        return this.http.get<KycInvoiceDTO[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<KycInvoiceDTO>> {

        return this.http.get<Page<KycInvoiceDTO>>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<KycInvoiceDTO>> {

        return this.http.get<Page<KycInvoiceDTO>>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(invoice: KycInvoiceDTO | any ): Observable<KycInvoiceDTO> {

        return this.http.post<KycInvoiceDTO>(`${this.path}`, invoice);
    }

    public search(criteria: string | any ): Observable<KycInvoiceDTO[]> {

        return this.http.get<KycInvoiceDTO[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
