// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { KycSubscriptionDTO } from '@app/model/bw/co/centralkyc/subscription/kyc-subscription-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class KycSubscriptionApi {
    
    protected path = '/subscription';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<RestApiResponse<KycSubscriptionDTO | any>> {

        return this.http.get<KycSubscriptionDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<RestApiResponse<KycSubscriptionDTO[] | any[]>> {

        return this.http.get<KycSubscriptionDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<RestApiResponse<Page<KycSubscriptionDTO> | any>> {

        return this.http.get<Page<KycSubscriptionDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: string | any , pageNumber: number | any , pageSize: number | any ): Observable<RestApiResponse<Page<KycSubscriptionDTO> | any>> {

        return this.http.get<Page<KycSubscriptionDTO> | any>(`${this.path}/search/paged?criteria=${criteria}&pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<RestApiResponse<boolean | any>> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(subscription: KycSubscriptionDTO | any ): Observable<RestApiResponse<KycSubscriptionDTO | any>> {

        return this.http.post<KycSubscriptionDTO | any>(`${this.path}`, subscription);
    }

    public search(criteria: string | any ): Observable<RestApiResponse<KycSubscriptionDTO[] | any[]>> {

        return this.http.get<KycSubscriptionDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
