// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, signal, linkedSignal, ViewChild, WritableSignal } from '@angular/core';
import { OrganisationDetailsComponent } from '@app/views/organisation/organisation-details';
import { OrganisationDetailsVarsForm } from '@app/views/organisation/organisation-details';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule, CurrencyPipe, DatePipe } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { BranchDTO } from '@models/bw/co/centralkyc/organisation/branch/branch-dto';
import { MatDialog, MatDialogConfig } from '@angular/material/dialog';
import { MatPaginator, PageEvent } from '@angular/material/paginator';
import { Router } from '@angular/router';
import { TableComponent } from '@app/components/table/table';
import { Loader } from '@app/@shared/loader/loader';
import { BranchApi } from '@app/services/bw/co/centralkyc/organisation/branch/branch-api';
import { ClientRequestApi } from '@app/services/bw/co/centralkyc/organisation/client/client-request-api';
import { ClientRequestDTO } from '@app/models/bw/co/centralkyc/organisation/client/client-request-dto';
import { ColumnModel } from '@app/models/column.model';
import { OrganisationDTO } from '@app/models/bw/co/centralkyc/organisation/organisation-dto';
import { Page } from '@app/models/page.model';
import { DialogComponent } from '@app/components/dialog/dialog';
import { BranchEditorImplComponent } from '@app/components/organisation/branch/branch-editor-impl';
import { ActionTemplate } from '@app/models/action-template';
import { KycSubscriptionDTO } from '@app/models/bw/co/centralkyc/subscription/kyc-subscription-dto';
import { KycInvoiceDTO } from '@app/models/bw/co/centralkyc/invoice/kyc-invoice-dto';

@Component({
  selector: 'app-organisation-details',
  templateUrl: './organisation-details.html',
  styleUrls: ['./organisation-details.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
  ],
  providers: [DatePipe, CurrencyPipe],
})
export class OrganisationDetailsImplComponent extends OrganisationDetailsComponent {
  // organisationApiStore = inject(OrganisationApiStore);
  // branchApiStore = inject(BranchApiStore);
  branchApi = inject(BranchApi);
  // kycInvoiceApiStore = inject(KycInvoiceApiStore);
  // kycSubscriptionApiStore = inject(KycSubscriptionApiStore);
  // clientRequestApiStore = inject(ClientRequestApiStore);
  clientRequestApi = inject(ClientRequestApi);
  datePipe = inject(DatePipe);
  currencyPipe = inject(CurrencyPipe);

  override error = linkedSignal(() => false);
  override messages = linkedSignal(() => false);
  override success = linkedSignal(() => false);
  organisation = linkedSignal(() => new OrganisationDTO())

  // Branches related properties
  branches = linkedSignal<BranchDTO[]>(() => []);
  branchesLoading = linkedSignal(() => false);
  currentPage = signal(0);
  pageSize = signal(10);
  totalBranches = signal(0);

  // Invoices related properties
  invoices = linkedSignal<KycInvoiceDTO[]>(() => []);
  invoicesLoading = linkedSignal(() => false);

  // Subscriptions related properties
  subscriptions = linkedSignal<KycSubscriptionDTO[]>(() => []);
  subscriptionsLoading = linkedSignal(() => false);

  // Client Requests related properties
  clientRequests = linkedSignal(() => new Page<ClientRequestDTO>());
  clientsTablePaged = signal(true);
  clientRequestsLoading = linkedSignal(() => false);
  uploadedClientRequestFiles = signal<any[]>([]);
  isUploadingClientRequestFile = signal(false);
  clientRequestFileUploadProgress = signal(0);

  // clientRequestsTable!: TableComponent<ClientRequestDTO>;


  // Client Requests Table Configuration
  // clientRequestsTablePaged: WritableSignal<boolean> = linkedSignal(() => true);
  // clientRequestsTableColumns: ColumnModel[] = [
  //   new ColumnModel('name', 'name', false),
  //   new ColumnModel('identityType', 'identity.type', false),
  //   new ColumnModel('identityNo', 'identity.no', false),
  //   new ColumnModel('status', 'status', false),
  // ];

  // clientRequestsTableColumnsActions: ActionTemplate[] = [
  //   {
  //     id: 'client-request-view',
  //     label: 'view',
  //     icon: 'visibility',
  //     tooltip: 'view',
  //   },
  //   {
  //     id: 'client-request-edit',
  //     label: 'edit',
  //     icon: 'edit',
  //     tooltip: 'edit',
  //   },
  // ];


  constructor() {
    super();

    // Effect to load branches when organisation is loaded
    effect(() => {
      const org = this.organisation();
      if (org?.id) {
        this.loadBranches();
        this.loadInvoices();
        this.loadSubscriptions();
        this.loadClientRequests();
      }
    });

    // Effect to update total branches count
    // effect(() => {
    //   const branchList = this.branches();
    //   if (branchList) {
    //     this.totalBranches.set(branchList.length);
    //   }
    // });
  }

  // showClientRequestsActions = false;

  @ViewChild('clientRequestsTable') set clientRequestsTableComp(clientRequestsTable: TableComponent<ClientRequestDTO> | undefined) {
  if (clientRequestsTable) {
    // this.clientRequestsTable = clientRequestsTable;
    // Do something when child is created
    this.clientRequestsTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        console.log('Paginator event:', paginator);
        this.doSearchRequests(paginator.pageIndex, paginator.pageSize);
      },
    });
  }
}

  override beforeOnInit(form: OrganisationDetailsVarsForm): OrganisationDetailsVarsForm {
    // this.organisationApiStore.reset();
    // this.branchApiStore.reset();
    // this.kycInvoiceApiStore.reset();
    // this.kycSubscriptionApiStore.reset();
    // this.clientRequestApiStore.reset();

    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        // this.organisationApiStore.findById(params);
      }
    });
    return form;
  }

  // override doNgAfterViewInit(): void {
  //   this.doSearchRequests();
  // }

  private doSearchRequests(pageNumber: number = 0, pageSize: number = 10): void {
    let org = this.organisation();
    if (org?.id) {
      this.loading.set(true)
      this.clientRequestApi.findByOrganisationPaged(
        org.id,
        pageNumber,
        pageSize,
      ).subscribe({
        next: (page) => {
          this.clientRequestsTableSignal.set(page);
          this.loading.set(false);
        }, 
        error: (error) => {

        }
      });
    }
  }

  // Branches Management Methods
  loadBranches(): void {
    const org = this.organisation();
    if (org?.id) {
      // this.branchApiStore.findByOrganisation({ organisationId: org.id });
    }
  }

  refreshBranches(): void {
    this.loadBranches();
  }

  // Invoices Management Methods
  loadInvoices(): void {
    const org = this.organisation();
    if (org?.id) {
      // this.kycInvoiceApiStore.findByOrganisation({ organisationId: org.id });
    }
  }

  refreshInvoices(): void {
    this.loadInvoices();
  }

  // Subscriptions Management Methods
  loadSubscriptions(): void {
    const org = this.organisation();
    if (org?.id) {
      // this.kycSubscriptionApiStore.findByOrganisation({ organisationId: org.id });
    }
  }

  refreshSubscriptions(): void {
    this.loadSubscriptions();
  }

  doEditBranch(branch: BranchDTO): void {
    // const dialogRef = this.dialog.open(DialogComponent<BranchEditorImplComponent>, <MatDialogConfig>{
    //   hasBackdrop: true,
    //   closeOnNavigation: true,
    //   disableClose: true,
    //   width: '800px',
    //   data: {
    //     component: BranchEditorImplComponent,
    //     title: 'Edit Section',
    //     inputs: {
    //       branchEditorForm: branch,
    //     },
    //     actions: [
    //       {
    //         id: 'save',
    //         label: 'Save',
    //         icon: 'save',
    //         tooltip: 'Save Section',
    //       },
    //     ],
    //   },
    // });

    // dialogRef.afterClosed().subscribe({
    //   next: (data) => {
    //     console.log('Dialog closed with data:', data);
    //     if (data?.action === 'save') {
    //       this.branchApi.save(data.value).subscribe({
    //         next: (field) => {
    //           // this.toastr.success('Field saved successfully');
    //           this.loadBranches();
    //         },
    //         error: (err) => {
    //           console.error('Error saving field:', err);
    //           // this.toastr.error('Error saving field');
    //         },
    //       });
    //     }
    //   },
    // });
  }

  addNewBranch(): void {
    let branch = new BranchDTO();
    const org = this.organisation();
    branch.organisationId = org.id;
    branch.organisation = org.name;

    this.doEditBranch(branch);
  }

  deleteBranch(branchId: string): void {
    if (confirm('Are you sure you want to delete this branch?')) {
      // this.branchApiStore.remove({ id: branchId });
      // Reload branches after deletion
      setTimeout(() => {
        this.loadBranches();
      }, 1000);
    }
  }

  onPageChange(event: PageEvent): void {
    this.currentPage.set(event.pageIndex);
    this.pageSize.set(event.pageSize);
    // Here you would typically load the specific page of branches
    // For now, we'll just update the pagination state
  }

  doNgOnDestroy(): void {}

  branchTablePaged = signal(false);
  // branchesTableColumns: ColumnModel[] = [
  //   new ColumnModel('code', 'code', false),
  //   new ColumnModel('name', 'name', false),
  // ];

  // branchesTableColumnsActions: ActionTemplate[] = [
  //   {
  //     id: 'branch-edit',
  //     label: 'edit',
  //     icon: 'edit',
  //     tooltip: 'edit',
  //   },
  //   {
  //     id: 'branch-delete',
  //     label: 'delete',
  //     icon: 'delete',
  //     tooltip: 'delete',
  //   },
  // ];

  branchesTableActionClicked(event: any): void {
    console.log(event);

    switch (event.action) {
      case 'branch-edit':
        // TODO: Implement the action
        this.doEditBranch(event.row);
        break;
      case 'branch-delete':
        // TODO: Implement the action
        this.deleteBranch(event.id);
        break;
    }
  }

  // Invoices Table Configuration
  invoicesTablePaged = signal(false);
  invoicesTableColumns: ColumnModel[] = [
    new ColumnModel('ref', 'ref', false),
    new ColumnModel('amount', 'amount', false, undefined, this.currencyPipe, ['BWP']),
    new ColumnModel('paid', 'paid', false),
    new ColumnModel('paymentReference', 'payment.reference', false),
  ];

  invoicesTableColumnsActions: ActionTemplate[] = [
    {
      id: 'invoice-view',
      label: 'view',
      icon: 'visibility',
      tooltip: 'view',
    },
  ];

  invoicesTableActionClicked(event: any): void {
    console.log(event);

    switch (event.action) {
      case 'invoice-view':
        this.router.navigate(['/invoice/details'], { queryParams: { id: event.row.id } });
        break;
    }
  }

  // Subscriptions Table Configuration
  subscriptionsTablePaged = signal(false);
  subscriptionsTableColumns: ColumnModel[] = [
    new ColumnModel('ref', 'ref', false),
    new ColumnModel('period', 'period', false),
    new ColumnModel('amount', 'amount', false, undefined, this.currencyPipe, ['BWP']),
    new ColumnModel('startDate', 'start.date', false, undefined, this.datePipe, ['dd/MM/yyyy']),
    new ColumnModel('endDate', 'end.date', false, undefined, this.datePipe, ['dd/MM/yyyy']),
    new ColumnModel('status', 'status', false),
  ];

  subscriptionsTableColumnsActions: ActionTemplate[] = [
    {
      id: 'subscription-view',
      label: 'view',
      icon: 'visibility',
      tooltip: 'view',
    },
  ];

  subscriptionsTableActionClicked(event: any): void {
    console.log(event);

    switch (event.action) {
      case 'subscription-view':
        this.router.navigate(['/subscription/details'], { queryParams: { id: event.row.id } });
        break;
    }
  }

  // Client Requests Management Methods
  loadClientRequests(): void {
    const org = this.organisation();
    if (org?.id) {
      this.doSearchRequests(0, 10);
    }
  }

  refreshClientRequests(): void {
    this.loadClientRequests();
  }

  addNewClientRequest(): void {
    this.router.navigate(['/client-request/edit'], {
      queryParams: { organisationId: this.organisation().id },
    });
  }
  clientRequestsTableActionClicked(event: any): void {
    console.log(event);

    switch (event.action) {
      case 'client-request-view':
        this.router.navigate(['/client-request/details'], { queryParams: { id: event.row.id } });
        break;
      case 'client-request-edit':
        this.router.navigate(['/client-request/edit'], { queryParams: { id: event.row.id } });
        break;
    }
  }

  // Client Request File Upload Methods
  onClientRequestFileSelected(event: any): void {
    const files: FileList = event.target.files;
    if (files && files.length > 0) {
      this.isUploadingClientRequestFile.set(true);
      this.clientRequestFileUploadProgress.set(0);

      // Simulate file upload progress
      const interval = setInterval(() => {
        const currentProgress = this.clientRequestFileUploadProgress();
        if (currentProgress < 100) {
          this.clientRequestFileUploadProgress.set(currentProgress + 10);
        } else {
          clearInterval(interval);

          // Add files to the uploaded list
          const newFiles = Array.from(files).map((file, index) => ({
            id: `file-${Date.now()}-${index}`,
            fileName: file.name,
            fileSize: file.size,
            file: file,
          }));

          this.uploadedClientRequestFiles.set([...this.uploadedClientRequestFiles(), ...newFiles]);
          this.isUploadingClientRequestFile.set(false);
          this.clientRequestFileUploadProgress.set(0);

          // Reset the file input
          event.target.value = '';
        }
      }, 300);

      // TODO: Implement actual file upload to server
      // this.clientRequestApiStore.uploadRequests({ file: files[0], organisationId: this.organisation().id });
    }
  }

  formatFileSize(bytes: number): string {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
  }

  downloadClientRequestFile(file: any): void {
    // Create a blob URL and trigger download
    const url = window.URL.createObjectURL(file.file);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.fileName;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);

    // TODO: Implement actual file download from server
    // this.clientRequestApiStore.downloadFile({ fileId: file.id });
  }

  deleteClientRequestFile(fileId: string): void {
    if (confirm('Are you sure you want to delete this file?')) {
      const currentFiles = this.uploadedClientRequestFiles();
      const updatedFiles = currentFiles.filter((f) => f.id !== fileId);
      this.uploadedClientRequestFiles.set(updatedFiles);

      // TODO: Implement actual file deletion from server
      // this.clientRequestApiStore.deleteFile({ fileId });
    }
  }

  downloadRequestTemplate(): void {
    // TODO: Optionally fetch template from server if backend provides a specific format
    this.clientRequestApi.downloadRequestTemplate().subscribe({
      next: (blob: Blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'client_requests_template.xlsx';
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      },
      error: (err) => {
        console.error('Error downloading template:', err);
      },
    });
  }

  override organisationDetailsEdit(): void {
    this.router.navigate(['/organisation/edit'], { queryParams: { id: this.organisation().id } });
  }
}
