// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { OrganisationDetailsComponent } from '@views/organisation/organisation-details';
import { OrganisationDetailsVarsForm } from '@views/organisation/organisation-details';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';

@Component({
  selector: 'app-organisation-details',
  templateUrl: './organisation-details.html',
  styleUrls: ['./organisation-details.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class OrganisationDetailsImplComponent extends OrganisationDetailsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: OrganisationDetailsVarsForm): OrganisationDetailsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}