// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, linkedSignal } from '@angular/core';
import { SearchOrganisationsComponent } from '@views/organisation/search-organisations';
import { SearchOrganisationsVarsForm } from '@views/organisation/search-organisations';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { Loader } from "@shared/loader/loader";
import { Field } from '@angular/forms/signals';
import { MatPaginator } from '@angular/material/paginator';
import { SearchObject } from '@app/models/search-object';
import { OrganisationSearchCriteria } from '@app/models/bw/co/centralkyc/organisation/organisation-search-criteria';
import { Page } from '@app/models/page.model';
import { OrganisationListDTO } from '@app/models/bw/co/centralkyc/organisation/organisation-list-dto';

@Component({
  selector: 'app-search-organisations',
  templateUrl: './search-organisations.html',
  styleUrls: ['./search-organisations.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    Field,
  ],
})
export class SearchOrganisationsImplComponent extends SearchOrganisationsComponent {


    override error = linkedSignal(() => false);
  override messages = linkedSignal(() => false);
  override success = linkedSignal(() => false);
  override loading = linkedSignal(() => false);

  override organisationsTableSignal = linkedSignal(() => new Page<OrganisationListDTO>());

  constructor() {
    super();

  }

    override beforeOnInit(form: SearchOrganisationsVarsForm): SearchOrganisationsVarsForm{     
        return form;
    }

  override ngOnInit() {
  }

  override doNgAfterViewInit(): void {
    this.organisationsTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        this.doSearch(paginator.pageIndex, paginator.pageSize);
      },
    });

    this.doSearch();
  }

  doNgOnDestroy(): void {}

  override beforeSearchOrganisationsSearch(form: any): void {
    this.doSearch();
  }

  private doSearch(pageNumber: number = 0, pageSize: number = 10): void {
    let value = this.searchOrganisationsSignal().criteria;

    let criteria = new SearchObject<OrganisationSearchCriteria>()
    criteria.pageNumber = pageNumber;
    criteria.pageSize = pageSize;
    criteria.criteria = value;

    this.organisationApi.pagedSearch(
      criteria
    ).subscribe({
      next: (orgPage: Page<OrganisationListDTO>) => {
        this.organisationsTableSignal.set(orgPage);
      },
      error: (error) => {
        console.log(error);
        this.toaster.error(
          error.error?.message ? error.error.message : error.message
        )
        this.loading.set(false);
      }
    });
  }
}