// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.organisation.client;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.DocumentApi;
import bw.co.centralkyc.document.DocumentDTO;
import bw.co.centralkyc.settings.SettingsDTO;
import bw.co.centralkyc.settings.SettingsService;

import java.io.InputStream;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.InputStreamResource;
import org.springframework.core.io.Resource;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class ClientRequestApiImpl extends ClientRequestApiBase {
    
    private final SettingsService settingsService;
    private final DocumentApi documentApi;

    public ClientRequestApiImpl(
        ClientRequestService clientRequestService,
        SettingsService settingsService,
        DocumentApi documentApi) {
        
        super(clientRequestService);
        this.settingsService = settingsService;
        this.documentApi = documentApi;
    }

    @Override
    public ResponseEntity<ClientRequestDTO> handleFindById(String id) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> handleFindByIndividual(String individualId) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.findByIndividual(individualId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handleFindByIndividualPaged(String individualId, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.findByIndividual(individualId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> handleFindByOrganisation(String organisationId) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.findByOrganisation(organisationId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handleFindByOrganisationPaged(String organisationId, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.findByOrganisation(organisationId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> handleFindByStatus(ClientRequestStatus status) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.findByStatus(status));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> handleGetAll() throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handleGetAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handlePagedSearch(SearchObject<ClientRequestSearchCriteria> criteria) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Boolean> handleRemove(String id) throws Exception {
        try {
            return ResponseEntity.ok(clientRequestService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<ClientRequestDTO> handleSave(ClientRequestDTO clientRequest) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(clientRequest, authentication);
            return ResponseEntity.ok(clientRequestService.save(clientRequest));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> handleSearch(SearchObject<ClientRequestSearchCriteria> criteria) throws Exception {
        try {
            Set<PropertySearchOrder> sorting = new HashSet<>();
            if(criteria.getSortings() != null) {

                sorting.addAll(criteria.getSortings());
            }

            return ResponseEntity.ok(clientRequestService.search(criteria.getCriteria(), sorting));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> handleFindByDocument(String documentId) throws Exception {
        
        try {
            return ResponseEntity.ok(clientRequestService.findByDocument(documentId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handleFindByDocumentPaged(String documentId, Integer pageNumber,
            Integer pageSize) throws Exception {
        
        try {
            return ResponseEntity.ok(clientRequestService.findByDocument(documentId, pageNumber, pageSize));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handleFindByStatusPaged(ClientRequestStatus status,
            Integer pageNumber, Integer pageSize) throws Exception {
        
        try {
            return ResponseEntity.ok(clientRequestService.findByStatus(status, pageNumber, pageSize));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> handleUploadRequests(MultipartFile file, String organisationId) throws Exception {

        try(InputStream inputStream = file.getInputStream()) {

            SettingsDTO settings = settingsService.getAll().stream().findFirst()
                    .orElseThrow(() -> new Exception("Settings not found"));
            
            DocumentDTO doc = documentApi
                    .upload(
                            TargetEntity.CLIENT_REQUEST,
                            settings.getId(),
                            settings.getClientRequestFileType().getId(),
                            file)
                    .getBody();

            return ResponseEntity.ok(clientRequestService.uploadRequests(inputStream, doc.getCreatedBy(), organisationId, doc));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

        @Override
    public ResponseEntity<InputStreamResource> handleDownloadRequestTemplate() throws Exception {
        
        try {
            // Read the individual template file from resources
            Resource resource = new ClassPathResource("templates/client-request-template.xlsx");
            
            if (!resource.exists()) {
                // Try CSV template as fallback
                resource = new ClassPathResource("templates/client-request-template.csv");
            }
            
            if (!resource.exists()) {
                throw new Exception("Template file not found in resources/templates directory");
            }
            
            InputStream inputStream = resource.getInputStream();
            InputStreamResource inputStreamResource = new InputStreamResource(inputStream);
            
            // Determine content type based on file extension
            String filename = resource.getFilename();
            MediaType mediaType = MediaType.APPLICATION_OCTET_STREAM;
            if (filename != null) {
                if (filename.endsWith(".xlsx")) {
                    mediaType = MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                } else if (filename.endsWith(".xls")) {
                    mediaType = MediaType.parseMediaType("application/vnd.ms-excel");
                } else if (filename.endsWith(".csv")) {
                    mediaType = MediaType.parseMediaType("text/csv");
                }
            }
            
            // Set headers for file download
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(mediaType);
            headers.setContentDispositionFormData("attachment", filename);
            headers.setCacheControl("must-revalidate, post-check=0, pre-check=0");
            
            return ResponseEntity.ok()
                    .headers(headers)
                    .contentLength(resource.contentLength())
                    .body(inputStreamResource);
                    
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
}