// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.organisation.client;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.DocumentApi;
import bw.co.centralkyc.document.DocumentDTO;
import bw.co.centralkyc.invoice.KycInvoiceDTO;
import bw.co.centralkyc.keycloak.KeycloakOrganisationService;
import bw.co.centralkyc.organisation.OrganisationDTO;
import bw.co.centralkyc.settings.SettingsDTO;
import bw.co.centralkyc.settings.SettingsService;

import java.io.InputStream;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.InputStreamResource;
import org.springframework.core.io.Resource;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class ClientRequestApiImpl implements ClientRequestApi {

    private final SettingsService settingsService;
    private final DocumentApi documentApi;
    private final ClientRequestService clientRequestService;
    // private final KeycloakOrganisationService keycloakOrganisationService;

    public ClientRequestApiImpl(
            ClientRequestService clientRequestService,
            SettingsService settingsService,
            DocumentApi documentApi) {

        this.settingsService = settingsService;
        this.documentApi = documentApi;
        this.clientRequestService = clientRequestService;
    }

    @Override
    public ResponseEntity<ClientRequestDTO> findById(String id) throws Exception {
        try {

            ClientRequestDTO request = clientRequestService.findById(id);

            return ResponseEntity.ok(request);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findByIndividual(String individualId) throws Exception {
        try {
            Collection<ClientRequestDTO> requests = clientRequestService.findByIndividual(individualId);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findByIndividualPaged(String individualId, Integer pageNumber,
            Integer pageSize) throws Exception {
        try {
            Page<ClientRequestDTO> requests = clientRequestService.findByIndividual(individualId, pageNumber, pageSize);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findByOrganisation(String organisationId, TargetEntity target)
            throws Exception {
        try {
            Collection<ClientRequestDTO> requests = clientRequestService.findByOrganisation(organisationId);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findByOrganisationPaged(String organisationId, Integer pageNumber,
            Integer pageSize, TargetEntity target) throws Exception {
        try {
            Page<ClientRequestDTO> requests = clientRequestService.findByOrganisation(organisationId, pageNumber,
                    pageSize);

            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findByStatus(ClientRequestStatus status) throws Exception {
        try {
            Collection<ClientRequestDTO> requests = clientRequestService.findByStatus(status);

            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> getAll() throws Exception {
        try {
            Collection<ClientRequestDTO> requests = clientRequestService.getAll();
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            Page<ClientRequestDTO> requests = clientRequestService.getAll(pageNumber, pageSize);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> pagedSearch(SearchObject<ClientRequestSearchCriteria> criteria)
            throws Exception {
        try {
            Page<ClientRequestDTO> requests = clientRequestService.search(criteria);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {

            return ResponseEntity.ok(clientRequestService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<ClientRequestDTO> save(ClientRequestDTO clientRequest) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(clientRequest, authentication);

            ClientRequestDTO savedRequest = clientRequestService.save(clientRequest);
            return ResponseEntity.ok(savedRequest);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> search(SearchObject<ClientRequestSearchCriteria> criteria)
            throws Exception {
        try {
            Set<PropertySearchOrder> sorting = new HashSet<>();
            if (criteria.getSortings() != null) {

                sorting.addAll(criteria.getSortings());
            }

            Collection<ClientRequestDTO> requests = clientRequestService.search(criteria.getCriteria(), sorting);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findByDocument(String documentId) throws Exception {

        try {
            Collection<ClientRequestDTO> requests = clientRequestService.findByDocument(documentId);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findByDocumentPaged(String documentId, Integer pageNumber,
            Integer pageSize) throws Exception {

        try {
            Page<ClientRequestDTO> requests = clientRequestService.findByDocument(documentId, pageNumber, pageSize);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findByStatusPaged(ClientRequestStatus status,
            Integer pageNumber, Integer pageSize) throws Exception {

        try {
            Page<ClientRequestDTO> requests = clientRequestService.findByStatus(status, pageNumber, pageSize);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> uploadRequests(MultipartFile file, String organisationId,
            TargetEntity target) throws Exception {

        try (InputStream inputStream = file.getInputStream()) {

            SettingsDTO settings = settingsService.getAll().stream().findFirst()
                    .orElseThrow(() -> new Exception("Settings not found"));

            DocumentDTO doc = documentApi
                    .upload(
                            TargetEntity.CLIENT_REQUEST,
                            settings.getId(),
                            settings.getClientRequestFileType().getId(),
                            file)
                    .getBody();

            // OrganisationDTO org = keycloakOrganisationService.findById(organisationId);
            // Page<ClientRequestDTO> requests = clientRequestService.uploadRequests(inputStream, organisationId,
            //         organisationId, doc, target, org.getName());
            // updateOrganisationsDetails(requests.getContent());

            return ResponseEntity.ok(null);
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<InputStreamResource> downloadRequestTemplate() throws Exception {

        try {
            // Read the individual template file from resources
            Resource resource = new ClassPathResource("templates/client-request-template.xlsx");

            if (!resource.exists()) {
                // Try CSV template as fallback
                resource = new ClassPathResource("templates/client-request-template.csv");
            }

            if (!resource.exists()) {
                throw new Exception("Template file not found in resources/templates directory");
            }

            InputStream inputStream = resource.getInputStream();
            InputStreamResource inputStreamResource = new InputStreamResource(inputStream);

            // Determine content type based on file extension
            String filename = resource.getFilename();
            MediaType mediaType = MediaType.APPLICATION_OCTET_STREAM;
            if (filename != null) {
                if (filename.endsWith(".xlsx")) {
                    mediaType = MediaType
                            .parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                } else if (filename.endsWith(".xls")) {
                    mediaType = MediaType.parseMediaType("application/vnd.ms-excel");
                } else if (filename.endsWith(".csv")) {
                    mediaType = MediaType.parseMediaType("text/csv");
                }
            }

            // Set headers for file download
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(mediaType);
            headers.setContentDispositionFormData("attachment", filename);
            headers.setCacheControl("must-revalidate, post-check=0, pre-check=0");

            return ResponseEntity.ok()
                    .headers(headers)
                    .contentLength(resource.contentLength())
                    .body(inputStreamResource);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findByTarget(TargetEntity target, String targetId)
            throws Exception {

        try {
            Collection<ClientRequestDTO> requests = clientRequestService.findByTarget(target, targetId);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findByTargetPaged(TargetEntity target,
            String targetId, Integer pageNumber, Integer pageSize) throws Exception {

        try {
            Page<ClientRequestDTO> requests = clientRequestService.findByTarget(target, targetId, pageNumber, pageSize);

            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findIndividualsByOrganisation(String organisationId)
            throws Exception {

        try {
            Collection<ClientRequestDTO> requests = clientRequestService
                    .findByTargetAndOrganisation(TargetEntity.INDIVIDUAL, null, organisationId);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findIndividualsByOrganisationPaged(String organisationId,
            Integer pageNumber, Integer pageSize) throws Exception {

        try {
            Page<ClientRequestDTO> requests = clientRequestService.findByTargetAndOrganisation(TargetEntity.INDIVIDUAL,
                    null, organisationId, pageNumber, pageSize);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<ClientRequestDTO>> findOrganisationsByOrganisation(String organisationId)
            throws Exception {
        try {
            Collection<ClientRequestDTO> requests = clientRequestService
                    .findByTargetAndOrganisation(TargetEntity.ORGANISATION, null, organisationId);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<ClientRequestDTO>> findOrganisationsByOrganisationPaged(String organisationId,
            Integer pageNumber, Integer pageSize) throws Exception {

        try {
            Page<ClientRequestDTO> requests = clientRequestService
                    .findByTargetAndOrganisation(TargetEntity.ORGANISATION, null, organisationId, pageNumber, pageSize);
            return ResponseEntity.ok(requests);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<ClientRequestDTO> updateStatus(String id, ClientRequestStatus status) throws Exception {

        try {

            ClientRequestDTO request = clientRequestService.updateStatus(id, status);
            return ResponseEntity.ok(request);

        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<String> confirmToken(String requestId, String token) throws Exception {

        try {

            String confirmationToken = clientRequestService.confirmToken(requestId, token);
            return ResponseEntity.ok(confirmationToken);

        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }
}