// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.kyc;

import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.Document;
import bw.co.centralkyc.document.DocumentDTO;
import bw.co.centralkyc.document.DocumentRepository;
import bw.co.centralkyc.individual.Individual;
import bw.co.centralkyc.individual.IndividualRepository;
import bw.co.centralkyc.individual.employment.EmploymentRecordRepository;
import jakarta.persistence.EntityNotFoundException;

import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Repository;

/**
 * @see KycRecord
 */
@Repository("kycRecordDao")
public class KycRecordDaoImpl
        extends KycRecordDaoBase {

    private final IndividualRepository individualRepository;

    public KycRecordDaoImpl(DocumentRepository documentRepository, IndividualRepository individualRepository,
            EmploymentRecordRepository employmentRecordRepository, KycRecordRepository kycRecordRepository) {
        super(documentRepository, employmentRecordRepository, kycRecordRepository);

        this.individualRepository = individualRepository;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toKycRecordDTO(
            KycRecord source,
            KycRecordDTO target) {
        // TODO verify behavior of toKycRecordDTO
        super.toKycRecordDTO(source, target);
        // WARNING! No conversion for target.documents (can't convert
        // source.getDocuments():bw.co.centralkyc.document.Document to
        // bw.co.centralkyc.document.DocumentDTO
        if (CollectionUtils.isNotEmpty(source.getDocuments())) {
            for (Document doc : source.getDocuments()) {
                DocumentDTO docDTO = new DocumentDTO();
                this.documentDao.toDocumentDTO(doc, docDTO);
                target.getDocuments().add(docDTO);
            }
        }

        if (source.getTarget() == TargetEntity.INDIVIDUAL && StringUtils.isNotBlank(source.getTargetId())) {

            Individual individual = individualRepository.findById(source.getTargetId())
                    .orElseThrow(() -> new KycRecordServiceException(
                            "Individual not found for id: " + source.getTargetId()));

            target.setIdentityNo(individual.getIdentityNo());

            StringBuilder builder = new StringBuilder();
            
            builder.append(individual.getFirstName());
            if (StringUtils.isNotBlank(individual.getMiddleName())) {
                builder.append(" ").append(individual.getMiddleName());
            }
            builder.append(" ").append(individual.getSurname());

            target.setName(builder.toString());

        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KycRecordDTO toKycRecordDTO(final KycRecord entity) {
        // TODO verify behavior of toKycRecordDTO
        return super.toKycRecordDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value
     * object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private KycRecord loadKycRecordFromKycRecordDTO(KycRecordDTO kycRecordDTO) {
        if (kycRecordDTO.getId() == null) {
            return KycRecord.Factory.newInstance();
        } else {
            return this.kycRecordRepository.findById(kycRecordDTO.getId())
                    .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + kycRecordDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public KycRecord kycRecordDTOToEntity(KycRecordDTO kycRecordDTO) {
        // TODO verify behavior of kycRecordDTOToEntity
        KycRecord entity = this.loadKycRecordFromKycRecordDTO(kycRecordDTO);
        this.kycRecordDTOToEntity(kycRecordDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void kycRecordDTOToEntity(
            KycRecordDTO source,
            KycRecord target,
            boolean copyIfNull) {
        // TODO verify behavior of kycRecordDTOToEntity
        super.kycRecordDTOToEntity(source, target, copyIfNull);

        if (CollectionUtils.isNotEmpty(source.getDocuments())) {
            for (DocumentDTO docDTO : source.getDocuments()) {
                Document doc = this.documentDao.documentDTOToEntity(docDTO);
                target.getDocuments().add(doc);
            }
        }

        if (source.getTarget() == TargetEntity.INDIVIDUAL && StringUtils.isNotBlank(source.getTargetId())) {

            this.individualRepository.findById(source.getTargetId())
                    .orElseThrow(() -> new KycRecordServiceException(
                            "Individual not found for id: " + source.getTargetId()));
        } else if (copyIfNull) {
            // target.setIndividual(null);
        }
    }
}