// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.individual;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import java.security.SecureRandom;
import java.util.Collection;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.email.EmailService;
import bw.co.centralkyc.keycloak.KeycloakOrganisationService;
import bw.co.centralkyc.keycloak.KeycloakUserService;
import bw.co.centralkyc.organisation.OrganisationDTO;
import bw.co.centralkyc.organisation.OrganisationListDTO;
import bw.co.centralkyc.organisation.branch.BranchDTO;
import bw.co.centralkyc.organisation.branch.BranchService;
import bw.co.centralkyc.user.UserDTO;
import bw.co.roguesystems.comm.ContentType;
import bw.co.roguesystems.comm.message.CommMessageDTO;

@org.springframework.web.bind.annotation.RestController
public class IndividualApiImpl extends IndividualApiBase {

    @Value("${app.organisation.manager-role}")
    private String organisationManagerRole;

    @Value("${app.security.password.min-length}")
    private int minPasswordLength;

    @Value("${app.admin-web}")
    private String adminWebUrl;

    private final KeycloakUserService keycloakUserService;
    private final KeycloakOrganisationService keycloakOrgService;
    private final BranchService branchService;
    private final EmailService emailService;

    private static final SecureRandom RANDOM = new SecureRandom();

    private static final String UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    private static final String LOWER = "abcdefghijklmnopqrstuvwxyz";
    private static final String DIGITS = "0123456789";
    private static final String SYMBOLS = "@#$%!";

    private static final String newUserTemplate = """
            Dear %s,

            Welcome to Central KYC platform. Your organisation, %s, has selected you to manage
            their account. This message alerts you that a user has been created for you on the
            platform. Please find the login details below:

            URL: %s
            Username: %s
            Password: %s

            Regards

            CentralKYC Team
            """;

    public IndividualApiImpl(IndividualService individualService, KeycloakUserService keycloakUserService,
            BranchService branchService, EmailService emailService, KeycloakOrganisationService keycloakOrgService) {

        super(individualService);
        this.keycloakUserService = keycloakUserService;
        this.branchService = branchService;
        this.emailService = emailService;
        this.keycloakOrgService = keycloakOrgService;
    }

    @Override
    public ResponseEntity<IndividualDTO> handleFindById(String id) {

        try {

            IndividualDTO data = individualService.findById(id);

            if (data.getHasUser()) {

                UserDTO user = keycloakUserService.getUserByIdentityNo(data.getIdentityNo());

                if (StringUtils.isNotBlank(user.getBranchId())) {

                    BranchDTO branch = branchService.findById(user.getBranchId());
                    data.setBranch(branch);
                }

                if (StringUtils.isNotBlank(user.getOrganisationId())) {

                    OrganisationListDTO orgList = new OrganisationListDTO();
                    orgList.setId(user.getOrganisationId());
                    orgList.setName(user.getOrganisation());

                    data.setOrganisation(orgList);
                }

            }

            return ResponseEntity.ok(data);
        } catch (Exception e) {
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<IndividualListDTO>> handleGetAll() {

        try {

            return ResponseEntity.ok(individualService.getAll());
        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<IndividualListDTO>> handleGetAllPaged(Integer pageNumber,
            Integer pageSize) {

        try {
            return ResponseEntity.ok(individualService.getAll(pageNumber, pageSize));

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<IndividualListDTO>> handlePagedSearch(
            SearchObject<IndividualSearchCriteria> criteria) {

        try {

            return ResponseEntity.ok(individualService.search(criteria));

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Boolean> handleRemove(String id) {

        try {

            return ResponseEntity.ok(individualService.remove(id));

        } catch (Exception e) {
            throw e;
        }

    }

    private String generatePassword() {
        if (minPasswordLength < 8) {
            throw new IllegalArgumentException("Password length must be at least 8");
        }

        List<String> groups = List.of(UPPER, LOWER, DIGITS, SYMBOLS);
        String all = UPPER + LOWER + DIGITS + SYMBOLS;

        StringBuilder password = new StringBuilder();

        // Ensure at least one char from each group
        for (String group : groups) {
            password.append(group.charAt(RANDOM.nextInt(group.length())));
        }

        // Fill remaining chars
        for (int i = password.length(); i < minPasswordLength; i++) {
            password.append(all.charAt(RANDOM.nextInt(all.length())));
        }

        return password.toString();
    }

    private CommMessageDTO newUserMessage(IndividualDTO individual, UserDTO user) {

        // OrganisationDTO org = keycloakOrgService.

        CommMessageDTO message = new CommMessageDTO();

        message.setContentType(ContentType.PLAIN_TEXT);
        message.setDestinations(List.of(individual.getEmailAddress()));

        StringBuilder nameBuilder = new StringBuilder();
        nameBuilder.append(individual.getFirstName()).append(' ');
        if (StringUtils.isNotBlank(individual.getMiddleName())) {

            nameBuilder.append(individual.getMiddleName()).append(' ');
        }

        nameBuilder.append(individual.getSurname());

        String messageStr = String.format(newUserTemplate, nameBuilder.toString(), individual.getOrganisation(),
                adminWebUrl, user.getUsername(),
                user.getPassword());

        message.setText(messageStr);

        return message;

    }

    @Override
    public ResponseEntity<IndividualDTO> handleSave(IndividualDTO individual) {

        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(individual, authentication);

            UserDTO user = keycloakUserService.getUserByIdentityNo(individual.getIdentityNo());
            boolean isNewUser = false;

            if (user == null) {

                UserDTO existing = keycloakUserService.getUserByEmail(individual.getEmailAddress());

                boolean createUser = isNewUser = existing == null;

                if (createUser) {

                    if (existing != null) {
                        boolean sameUser = existing.getFirstName().equals(individual.getFirstName())
                                && existing.getUsername().equals(individual.getSurname());

                        if (!sameUser) {

                            throw new IndividualServiceException(
                                    "The provided individual has an email used by a user who does not match the given information.");
                        }
                    }

                    user = new UserDTO();
                    user.setFirstName(individual.getFirstName());
                    user.setLastName(individual.getSurname());
                    user.setEmail(individual.getEmailAddress());
                    user.setUsername(individual.getEmailAddress());
                    user.setIdentityNo(individual.getIdentityNo());
                    user.setPassword(generatePassword());
                    user.setEnabled(true);
                    user.setBranchId(individual.getBranch().getId());
                    user.setBranch(individual.getBranch().getName());
                    user.setOrganisation(individual.getOrganisation().getName());
                    user.setOrganisationId(individual.getOrganisation().getId());
                    user.setRoles(Set.of(organisationManagerRole));

                    keycloakUserService.createUser(user);
                }

            }

            individual = individualService.save(individual);
            if (isNewUser) {
                emailService.sendEmail(List.of(newUserMessage(individual, user)));
            }

            return ResponseEntity.ok(individual);

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<IndividualListDTO>> handleSearch(
            SearchObject<IndividualSearchCriteria> criteria) {

        try {

            return ResponseEntity
                    .ok(individualService.search(criteria.getCriteria(), (PropertySearchOrder) criteria.getSortings()));

        } catch (Exception e) {
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<IndividualListDTO>> handleGetOrganisationClients(
            String organisationId) throws Exception {

        try {

            return ResponseEntity
                    .ok(null);

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<IndividualListDTO>> handleGetOrganisationClientsPaged(
            String criteria, Integer pageNumber, Integer pageSize) throws Exception {

        try {

            return ResponseEntity
                    .ok(null);

        } catch (Exception e) {
            throw e;
        }
    }
}