// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.individual;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import java.util.Collection;

import org.apache.commons.lang3.StringUtils;
import org.springframework.data.domain.Page;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;
import bw.co.centralkyc.keycloak.KeycloakUserService;
import bw.co.centralkyc.organisation.OrganisationListDTO;
import bw.co.centralkyc.organisation.branch.BranchDTO;
import bw.co.centralkyc.organisation.branch.BranchService;
import bw.co.centralkyc.user.UserDTO;

@org.springframework.web.bind.annotation.RestController
public class IndividualApiImpl extends IndividualApiBase {

    private final KeycloakUserService keycloakUserService;
    private final BranchService branchService;

    public IndividualApiImpl(IndividualService individualService, KeycloakUserService keycloakUserService,
            BranchService branchService) {

        super(individualService);
        this.keycloakUserService = keycloakUserService;
        this.branchService = branchService;
    }

    @Override
    public ResponseEntity<IndividualDTO> handleFindById(String id) {

        try {

            IndividualDTO data = individualService.findById(id);

            if (data.getHasUser()) {

                UserDTO user = keycloakUserService.getUserByIdentityNo(data.getIdentityNo());

                if (StringUtils.isNotBlank(user.getBranchId())) {

                    BranchDTO branch = branchService.findById(user.getBranchId());
                    data.setBranch(branch);
                }

                if (StringUtils.isNotBlank(user.getOrganisationId())) {

                    OrganisationListDTO orgList = new OrganisationListDTO();
                    orgList.setId(user.getOrganisationId());
                    orgList.setName(user.getOrganisation());

                    data.setOrganisation(orgList);
                }

            }

            return ResponseEntity.ok(data);
        } catch (Exception e) {
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<IndividualListDTO>> handleGetAll() {

        try {

            return ResponseEntity.ok(individualService.getAll());
        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<IndividualListDTO>> handleGetAllPaged(Integer pageNumber,
            Integer pageSize) {

        try {
            return ResponseEntity.ok(individualService.getAll(pageNumber, pageSize));

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<IndividualListDTO>> handlePagedSearch(
            SearchObject<IndividualSearchCriteria> criteria) {

        try {

            return ResponseEntity.ok(individualService.search(criteria));

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Boolean> handleRemove(String id) {

        try {

            return ResponseEntity.ok(individualService.remove(id));

        } catch (Exception e) {
            throw e;
        }

    }

    @Override
    public ResponseEntity<IndividualDTO> handleSave(IndividualDTO individual) {

        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(individual, authentication);

            keycloakUserService.getUserByIdentityNo(individual.getIdentityNo());
            UserDTO user = keycloakUserService.getUserByIdentityNo(individual.getIdentityNo());

            System.out.println("------------------------------->>>>>>>>>>>>> " + user);

            if (user == null) {

                UserDTO existing = keycloakUserService.getUserByEmail(individual.getEmailAddress());

                boolean createUser = existing == null;

                if (createUser) {

                    if (existing != null) {
                        boolean sameUser = existing.getFirstName().equals(individual.getFirstName())
                                && existing.getUsername().equals(individual.getSurname());

                        if (!sameUser) {

                            throw new IndividualServiceException(
                                    "The provided individual has an email used by a user who does not match the given information.");
                        }
                    }

                    user = new UserDTO();
                    user.setFirstName(individual.getFirstName());
                    user.setLastName(individual.getSurname());
                    user.setEmail(individual.getEmailAddress());
                    user.setUsername(individual.getEmailAddress());
                    user.setIdentityNo(individual.getIdentityNo());
                    user.setPassword("P@ssw0rd");
                    user.setEnabled(true);
                    user.setBranchId(individual.getBranch().getId());
                    user.setBranch(individual.getBranch().getName());
                    user.setOrganisation(individual.getOrganisation().getName());
                    user.setOrganisationId(individual.getOrganisation().getId());

                    user = keycloakUserService.createUser(user);
                }

            }

            return ResponseEntity.ok(individualService.save(individual));

        } catch (Exception e) {
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<IndividualListDTO>> handleSearch(
            SearchObject<IndividualSearchCriteria> criteria) {

        try {

            return ResponseEntity
                    .ok(individualService.search(criteria.getCriteria(), (PropertySearchOrder) criteria.getSortings()));

        } catch (Exception e) {
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<IndividualListDTO>> handleGetOrganisationClients(
            String organisationId) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'handleGetOrganisationClients'");
    }

    @Override
    public ResponseEntity<Page<IndividualListDTO>> handleGetOrganisationClientsPaged(
            String criteria, Integer pageNumber, Integer pageSize) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'handleGetOrganisationClientsPaged'");
    }
}