// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.centralkyc.organisation.client;

import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.DocumentRepository;
import bw.co.centralkyc.individual.Individual;
import bw.co.centralkyc.individual.IndividualRepository;
import jakarta.persistence.EntityNotFoundException;

import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Repository;

/**
 * @see ClientRequest
 */
@Repository("clientRequestDao")
public class ClientRequestDaoImpl
        extends ClientRequestDaoBase {

    private final IndividualRepository individualRepository;

    public ClientRequestDaoImpl(DocumentRepository documentRepository,
            ClientRequestRepository clientRequestRepository, IndividualRepository individualRepository) {
        super(documentRepository, clientRequestRepository);
        this.individualRepository = individualRepository;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toClientRequestDTO(
            ClientRequest source,
            ClientRequestDTO target) {
        Map<String, Individual> individualCache = new HashMap<>();

        // TODO verify behavior of toClientRequestDTO
        super.toClientRequestDTO(source, target);
        // WARNING! No conversion for target.organisation (can't convert
        // source.getOrganisation():bw.co.centralkyc.organisation.Organisation to
        // java.lang.String

        // if(source.getOrganisation() != null) {

        // target.setOrganisationId(source.getOrganisation().getId());
        // target.setOrganisation(source.getOrganisation().getName());
        // target.setOrganisationRegistrationNo(source.getOrganisation().getRegistrationNo());
        // }

        if (source.getTarget() == TargetEntity.INDIVIDUAL) {

            Individual individual = individualCache.get(source.getTargetId());

            if (individual == null) {

                individual = individualRepository.getReferenceById(source.getTargetId());
                individualCache.put(source.getTargetId(), individual);
            }

            // target.setIdentityNo(individual.getIdentityNo());
            target.setRegistration(individual.getIdentityNo());
            target.setIdentityType(individual.getIdentityType());

            StringBuilder nameBuilder = new StringBuilder();
            nameBuilder.append(individual.getFirstName());

            if (individual.getMiddleName() != null) {
                nameBuilder.append(" ");
                nameBuilder.append(individual.getMiddleName());
            }

            if (individual.getSurname() != null) {
                nameBuilder.append(" ");
                nameBuilder.append(individual.getSurname());
            }

            target.setName(nameBuilder.toString());

            target.setEmailAddress(individual.getEmailAddress());

        }

        if (source.getDocument() != null) {

            target.setDocumentId(source.getDocument().getId());
            target.setDocumentType(source.getDocument().getDocumentType().getName());
            target.setDocumentTypeId(source.getDocument().getDocumentType().getId());
            target.setFileName(source.getDocument().getFileName());
            target.setFileUrl(source.getDocument().getUrl());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientRequestDTO toClientRequestDTO(final ClientRequest entity) {
        // TODO verify behavior of toClientRequestDTO
        return super.toClientRequestDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value
     * object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private ClientRequest loadClientRequestFromClientRequestDTO(ClientRequestDTO clientRequestDTO) {

        System.out.println(clientRequestDTO);
        if (StringUtils.isEmpty(clientRequestDTO.getId())) {
            return ClientRequest.Factory.newInstance();
        } else {
            return this.clientRequestRepository.findById(clientRequestDTO.getId())
                    .orElseThrow(
                            () -> new EntityNotFoundException("Entity not found for id: " + clientRequestDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public ClientRequest clientRequestDTOToEntity(ClientRequestDTO clientRequestDTO) {
        // TODO verify behavior of clientRequestDTOToEntity
        ClientRequest entity = this.loadClientRequestFromClientRequestDTO(clientRequestDTO);
        this.clientRequestDTOToEntity(clientRequestDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void clientRequestDTOToEntity(
            ClientRequestDTO source,
            ClientRequest target,
            boolean copyIfNull) {
        // TODO verify behavior of clientRequestDTOToEntity
        super.clientRequestDTOToEntity(source, target, copyIfNull);

        if (StringUtils.isNotBlank(source.getDocumentId())) {

            target.setDocument(documentRepository.getReferenceById(source.getDocumentId()));
        }

        // if(StringUtils.isNotBlank(source.getIndividualId())) {

        // target.setIndividual(individualRepository.getReferenceById(source.getIndividualId()));

        // } else if(StringUtils.isNotBlank(source.getIdentityNo()) &&
        // source.getIdentityType() != null) {

        // target.setIndividual(
        // individualRepository.findByIdentityNoAndIdentityType(
        // source.getIdentityNo(),
        // source.getIdentityType()
        // )
        // );
        // }

        if(source.getTarget() == TargetEntity.INDIVIDUAL && StringUtils.isNotBlank(source.getTargetId())) {

            if(individualRepository.existsById(source.getTargetId())) {

                target.setTargetId(source.getTargetId());
            } else {

                throw new EntityNotFoundException("Individual not found for id: " + source.getTargetId());
            }
        }

        if (StringUtils.isNotBlank(source.getOrganisationId())) {

            target.setOrganisationId(source.getOrganisationId());
        }
    }
}