// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, computed, effect, inject, linkedSignal } from '@angular/core';
import { EditInvoiceComponent } from '@app/view/invoice/edit-invoice.component';
import { EditInvoiceVarsForm } from '@app/view/invoice/edit-invoice.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';
import { OrganisationApiStore } from '@app/store/bw/co/centralkyc/organisation/organisation-api.store';
import { OrganisationListDTO } from '@app/model/bw/co/centralkyc/organisation/organisation-list-dto';

@Component({
  selector: 'app-edit-invoice',
  templateUrl: './edit-invoice.component.html',
  styleUrls: ['./edit-invoice.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class EditInvoiceImplComponent extends EditInvoiceComponent {

  organisationApiStore = inject(OrganisationApiStore);

  override loading = computed(
    () => this.kycInvoiceApiStore.loading()
  );

  override organisationFilteredList = linkedSignal(() => this.organisationApiStore.dataList());

  override error = linkedSignal(() => this.kycInvoiceApiStore.error());
  override messages = linkedSignal(() => this.kycInvoiceApiStore.messages());
  override success = linkedSignal(() => this.kycInvoiceApiStore.success());

  invoice = this.kycInvoiceApiStore.data;

  override organisationDisplays: string[] = ['name'];

  constructor() {
    super();

    effect(() => {
      const invoice = this.kycInvoiceApiStore.data();

      if (!invoice) {
        return;
      }

      console.log('Invoice loaded in edit component:', invoice);
      this.editInvoiceForm.patchValue(invoice);

      if (invoice.organisationId) {

        console.log('Setting organisationFilteredList with organisationId:', invoice.organisationId);

        this.organisationControl.setValue({
          id: invoice.organisationId,
          name: invoice.organisationName,
          code: invoice.organisatonCode,
          registrationNo: invoice.organisationRegistrationNo
        });

        this.organisationFilteredList.set([{
          id: invoice.organisationId,
          name: invoice.organisationName,
          code: invoice.organisatonCode,
          registrationNo: invoice.organisationRegistrationNo
        }]);
      }
    });
  }

  override beforeOnInit(form: EditInvoiceVarsForm): EditInvoiceVarsForm {
    this.kycInvoiceApiStore.reset();

    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.kycInvoiceApiStore.findById(params);
      }
    });
    return form;
  }

  doNgOnDestroy(): void { }

  override organisationCompare(o1: OrganisationListDTO | any, o2: OrganisationListDTO | any) {
    return o1 && o2 ? o1.id === o2.id : false;
  }
}
