// Generated by andromda-angular cartridge (view\view.component.ts.vsl) DO NOT EDIT
import {
    Component,
    OnInit,
    effect,
    inject,
    ViewChild,
    Input,
    Output,
    EventEmitter,
    AfterViewInit,
    signal,
    Signal,
    linkedSignal,
    WritableSignal,
    OnDestroy,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import {COMMA, ENTER} from '@angular/cdk/keycodes';
import {
    FormGroup,
    FormControl,
    FormArray,
    FormBuilder,
    ReactiveFormsModule,
    Validators
} from '@angular/forms';
import { formatDate } from '@angular/common';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { Store, select } from '@ngrx/store';
import { Observable, of, Subscription } from 'rxjs';
import { SearchObject } from '@app/model/search-object';
import { MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';
import { MatChipInputEvent } from '@angular/material/chips';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { TableComponent } from '@app/components/table/table.component';
import { KycInvoiceApiStore } from '@app/store/bw/co/centralkyc/invoice/kyc-invoice-api.store';
import { ColumnModel } from '@app/model/column.model';
import { ActionTemplate } from '@app/model/action-template';

import { TargetEntity } from '@app/model/bw/co/centralkyc/target-entity';
import { OrganisationListDTO } from '@app/model/bw/co/centralkyc/organisation/organisation-list-dto';
import { TimePeriod } from '@app/model/bw/co/centralkyc/time-period';
import { KycInvoiceDTO } from '@app/model/bw/co/centralkyc/invoice/kyc-invoice-dto';
import { InvoiceControllerImpl } from '@app/controller/invoice/invoice-controller.impl';
import { KycInvoiceApi } from '@app/service/bw/co/centralkyc/invoice/kyc-invoice-api';
import { DocumentDTO } from '@app/model/bw/co/centralkyc/document/document-dto';
import { ToastrService } from 'ngx-toastr';
import { Page } from '@app/model/page.model';

export class InvoiceDetailsVarsForm {
    id?: string | any;
    createdAt?: Date | any;
    createdBy?: string | any;
    modifiedAt?: Date | any;
    modifiedBy?: string | any;
    ref?: string | any;
    organisationId?: string | any;
    organisationCode?: string | any;
    organisationName?: string | any;
    organisationRegistrationNo?: string | any;
    paid?: boolean | any;
    paymentReference?: string | any;
    amount?: number | any;
    invoiceDocument?: DocumentDTO | any;
    proofOfPayment?: DocumentDTO | any;
}

@Component({
  selector: 'app-invoice-details-base',
  template: ''
})
export abstract class InvoiceDetailsComponent implements OnInit, AfterViewInit, OnDestroy {

    separatorKeysCodes: number[] = [ENTER, COMMA];
    @Input() invoiceDetailsVarsForm: InvoiceDetailsVarsForm = {};

	invoiceDetailsForm: FormGroup = new FormGroup({});
    hide: boolean = false;
    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
    protected formBuilder: FormBuilder = inject(FormBuilder);
    protected useCaseScope: UseCaseScope = inject(UseCaseScope);
    dialog: MatDialog = inject(MatDialog);
    toaster: ToastrService = inject(ToastrService);
    invoiceController: InvoiceControllerImpl = inject(InvoiceControllerImpl);
    readonly kycInvoiceApiStore = inject(KycInvoiceApiStore);
    invoiceDocumentPreview: any = '';
    invoiceDocumentSelectedFile?: File;

    proofOfPaymentFilterCtrl: FormControl = new FormControl();

    proofOfPaymentCompare(o1: DocumentDTO | any, o2: DocumentDTO | any) {
        return false;
    }

    filterProofOfPayment() {}

    proofOfPaymentBackingList: DocumentDTO[] = [];
    proofOfPaymentFilteredList: WritableSignal<DocumentDTO[] | any[]> = linkedSignal(() => []);
    proofOfPaymentChipControl: FormControl = new FormControl([]);

    proofOfPaymentDisplays: string[] = [
        'target',
        'documentTypeId',
        'documentType',
        'url',
        'targetId',
        'metadata',
        'fileName',
    ];


    TargetEntityT: any = TargetEntity;
    TargetEntityOptions = Object.keys(this.TargetEntityT);
    TimePeriodT: any = TimePeriod;
    TimePeriodOptions = Object.keys(this.TimePeriodT);
    loaderMessage: Signal<string> = signal('');
    messages: Signal<string[]> = signal([]);
    success: Signal<boolean> = signal(false);
    loading: Signal<boolean> = signal(false);
    error: Signal<boolean> = signal(false);
    selected: Signal<any> = signal(null);

    invoiceDetailsFormValueSubscription?: Subscription;

    constructor() {


    effect(() => {
      let messages = this.messages();

      if(this.success() && !this.loading()) {
        this.toaster.success(messages[0]);
      }

      if (this.error() && !this.loading()) {
        this.toaster.error(messages[0]);
      }
    })
    }

    abstract beforeOnInit(form: InvoiceDetailsVarsForm): InvoiceDetailsVarsForm;

    ngOnInit() {
        let form: InvoiceDetailsVarsForm = this.beforeOnInit(new InvoiceDetailsVarsForm);
        this.invoiceDetailsForm = this.newForm(form);

        this.invoiceDetailsFormValueSubscription = this.invoiceDetailsForm.valueChanges.subscribe(
            (change: any) => {
                this.handleFormChanges(change);
            }
        );

        this.afterOnInit();
    }

    handleFormChanges(change: any): void {

    }

    invoiceDetailsFormReset() {

                this.invoiceDetailsForm.reset()
        this.invoiceDetailsForm.markAsPristine();

        if(this.router.url.substring(0, this.router.url.indexOf('?'))) {
            this.router.navigate([this.router.url.substring(0, this.router.url.indexOf('?'))]);
        } else {
            this.router.navigate([this.router.url]);
        }
    }

    afterOnInit(): void {}

    doNgAfterViewInit(): void {}

    ngAfterViewInit() {
        this.doNgAfterViewInit();
        this.invoiceController.resetUseCaseScope();
    }

    newForm(invoiceDetailsVarsForm: InvoiceDetailsVarsForm): FormGroup {
        return this.formBuilder.group({
            id: [{value: this.invoiceDetailsVarsForm.id, disabled: false}],
            createdAt: [{value: this.invoiceDetailsVarsForm.createdAt, disabled: false}],
            createdBy: [{value: this.invoiceDetailsVarsForm.createdBy, disabled: false}],
            modifiedAt: [{value: this.invoiceDetailsVarsForm.modifiedAt, disabled: false}],
            modifiedBy: [{value: this.invoiceDetailsVarsForm.modifiedBy, disabled: false}],
            ref: [{value: this.invoiceDetailsVarsForm.ref, disabled: false}],
            organisationId: [{value: this.invoiceDetailsVarsForm.organisationId, disabled: false}, [Validators.required, ]],
            organisationCode: [{value: this.invoiceDetailsVarsForm.organisationCode, disabled: false}, [Validators.required, ]],
            organisationName: [{value: this.invoiceDetailsVarsForm.organisationName, disabled: false}, [Validators.required, ]],
            organisationRegistrationNo: [{value: this.invoiceDetailsVarsForm.organisationRegistrationNo, disabled: false}, [Validators.required, ]],
            paid: [{value: this.invoiceDetailsVarsForm.paid, disabled: false}, [Validators.required, ]],
            paymentReference: [{value: this.invoiceDetailsVarsForm.paymentReference, disabled: false}, [Validators.required, ]],
            amount: [{value: this.invoiceDetailsVarsForm.amount, disabled: false}, [Validators.required, ]],
            invoiceDocument: this.createDocumentDTOGroup(this.invoiceDetailsVarsForm.invoiceDocument),
            proofOfPayment: [{value: this.invoiceDetailsVarsForm.proofOfPayment, disabled: false}],

        });
    }

    abstract doNgOnDestroy(): void;

    ngOnDestroy() {
        this.doNgOnDestroy();
        if(this.invoiceDetailsFormValueSubscription) {
            this.invoiceDetailsFormValueSubscription.unsubscribe();
        }
    }


    /**
     * This method may be overwritten
     */
    beforeInvoiceDetailsEdit(form: any): void {}

    /**
     * This method may be overwritten
     */
    afterInvoiceDetailsEdit(form: any): void {}

    /**
     * This method may be overwritten
     */
    get invoiceDetailsEditId(): string {
        return {} as string;
    }

    invoiceDetailsEdit(): void {

        let form: any = {
            id: this.invoiceDetailsEditId,
        };

        this.beforeInvoiceDetailsEdit(form);

        this.invoiceController.invoiceDetailsEdit(form.id);
        this.afterInvoiceDetailsEdit(form);
    }

    get invoiceDetailsVarsFormControl(): FormGroup {
        return this.getGroupControl('invoiceDetailsVarsForm');
    }


    get idControl(): FormControl {
        return this.invoiceDetailsForm?.get('id') as FormControl;
    }


    get createdAtControl(): FormControl {
        return this.invoiceDetailsForm?.get('createdAt') as FormControl;
    }


    get createdByControl(): FormControl {
        return this.invoiceDetailsForm?.get('createdBy') as FormControl;
    }


    get modifiedAtControl(): FormControl {
        return this.invoiceDetailsForm?.get('modifiedAt') as FormControl;
    }


    get modifiedByControl(): FormControl {
        return this.invoiceDetailsForm?.get('modifiedBy') as FormControl;
    }


    get refControl(): FormControl {
        return this.invoiceDetailsForm?.get('ref') as FormControl;
    }


    get organisationIdControl(): FormControl {
        return this.invoiceDetailsForm?.get('organisationId') as FormControl;
    }


    get organisationCodeControl(): FormControl {
        return this.invoiceDetailsForm?.get('organisationCode') as FormControl;
    }


    get organisationNameControl(): FormControl {
        return this.invoiceDetailsForm?.get('organisationName') as FormControl;
    }


    get organisationRegistrationNoControl(): FormControl {
        return this.invoiceDetailsForm?.get('organisationRegistrationNo') as FormControl;
    }


    get paidControl(): FormControl {
        return this.invoiceDetailsForm?.get('paid') as FormControl;
    }


    get paymentReferenceControl(): FormControl {
        return this.invoiceDetailsForm?.get('paymentReference') as FormControl;
    }


    get amountControl(): FormControl {
        return this.invoiceDetailsForm?.get('amount') as FormControl;
    }

    get invoiceDocumentControl(): FormGroup {
        return this.invoiceDetailsForm?.get('invoiceDocument') as FormGroup;
    }

    invoiceDocumentAddDialog(){}

    invoiceDocumentClear(){}

    invoiceDocumentSelected(event: MatCheckboxChange, row: number){}

    invoiceDocumentSearch(){}

    addSelectedInvoiceDocument(){}

    get invoiceDocumentTargetControl(): FormGroup {
        return this.invoiceDocumentControl?.get('target') as FormGroup;
    }

    get invoiceDocumentDocumentTypeIdControl(): FormControl {
        return this.invoiceDocumentControl?.get('documentTypeId') as FormControl;
    }

    get invoiceDocumentDocumentTypeControl(): FormControl {
        return this.invoiceDocumentControl?.get('documentType') as FormControl;
    }

    get invoiceDocumentUrlControl(): FormControl {
        return this.invoiceDocumentControl?.get('url') as FormControl;
    }

    get invoiceDocumentTargetIdControl(): FormControl {
        return this.invoiceDocumentControl?.get('targetId') as FormControl;
    }

    get invoiceDocumentMetadataControl(): FormControl {
        return this.invoiceDocumentControl?.get('metadata') as FormControl;
    }

    get invoiceDocumentFileNameControl(): FormControl {
        return this.invoiceDocumentControl?.get('fileName') as FormControl;
    }

    deleteFromSelectedInvoiceDocument() {
        // this.invoiceDocumentControl.setValue(null);
        this.invoiceDocumentPreview = null;
    }

    invoiceDocumentSelectFile(event: any): void {

        for (let i = 0; i < event.target.files.length; i++) {
            const file = event.target.files[i];

            this.invoiceDocumentControl.setValue(file);
        }
    }



    createDocumentDTOGroup(value?: DocumentDTO): FormGroup {
        return this.formBuilder.group({
            target: [value?.target],
            documentTypeId: [value?.documentTypeId],
            documentType: [value?.documentType],
            url: [value?.url],
            targetId: [value?.targetId],
            metadata: [value?.metadata],
            fileName: [value?.fileName],
            id: [value?.id],
            createdBy: [value?.createdBy],
            createdAt: [value?.createdAt],
            modifiedBy: [value?.modifiedBy],
            modifiedAt: [value?.modifiedAt],
        });
    }

    createDocumentDTOArray(values?: DocumentDTO[]): FormArray {
        if(values) {
            let formArray: FormArray = this.formBuilder.array([]);
            values?.forEach(value => formArray.push(this.createDocumentDTOGroup(value)))

            return formArray;
        } else {
            return new FormArray([] as any);
        }
    }

    get proofOfPaymentControl(): FormControl {
        return this.invoiceDetailsForm?.get('proofOfPayment') as FormControl;
    }

    proofOfPaymentAddDialog(){}

    proofOfPaymentClear(){}

    proofOfPaymentSelected(event: MatCheckboxChange, row: number){}

    proofOfPaymentSearch(){}

    addSelectedProofOfPayment(){}

    getItemControl(name: string): FormControl {
        return this.invoiceDetailsForm.get(name) as FormControl;
    }

    getGroupControl(name: string): FormGroup {
        return this.invoiceDetailsForm.get(name) as FormGroup;
    }

    getArrayControl(name: string): FormArray {
        return this.invoiceDetailsForm.get(name) as FormArray;
    }

    setInvoiceDetailsFormValue(form: any) {
        if(form.id) {
            this.invoiceDetailsForm?.get('id')?.setValue(form.id);
        }
        if(form.createdAt) {
            this.invoiceDetailsForm?.get('createdAt')?.setValue(form.createdAt);
        }
        if(form.createdBy) {
            this.invoiceDetailsForm?.get('createdBy')?.setValue(form.createdBy);
        }
        if(form.modifiedAt) {
            this.invoiceDetailsForm?.get('modifiedAt')?.setValue(form.modifiedAt);
        }
        if(form.modifiedBy) {
            this.invoiceDetailsForm?.get('modifiedBy')?.setValue(form.modifiedBy);
        }
        if(form.ref) {
            this.invoiceDetailsForm?.get('ref')?.setValue(form.ref);
        }
        if(form.organisationId) {
            this.invoiceDetailsForm?.get('organisationId')?.setValue(form.organisationId);
        }
        if(form.organisationCode) {
            this.invoiceDetailsForm?.get('organisationCode')?.setValue(form.organisationCode);
        }
        if(form.organisationName) {
            this.invoiceDetailsForm?.get('organisationName')?.setValue(form.organisationName);
        }
        if(form.organisationRegistrationNo) {
            this.invoiceDetailsForm?.get('organisationRegistrationNo')?.setValue(form.organisationRegistrationNo);
        }
        if(form.paid) {
            this.invoiceDetailsForm?.get('paid')?.setValue(form.paid);
        }
        if(form.paymentReference) {
            this.invoiceDetailsForm?.get('paymentReference')?.setValue(form.paymentReference);
        }
        if(form.amount) {
            this.invoiceDetailsForm?.get('amount')?.setValue(form.amount);
        }
        if(form.invoiceDocument) {
        }
        if(form.proofOfPayment) {
        }
    }


}
