// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, linkedSignal } from '@angular/core';
import { InvoicesComponent } from '@app/view/invoice/invoices.component';
import { InvoicesVarsForm } from '@app/view/invoice/invoices.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';
import { InvoiceSearchCriteria } from '@app/model/bw/co/centralkyc/invoice/invoice-search-criteria';
import { SearchObject } from '@app/model/search-object';
import { MatPaginator } from '@angular/material/paginator';

@Component({
  selector: 'app-invoices',
  templateUrl: './invoices.component.html',
  styleUrls: ['./invoices.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class InvoicesImplComponent extends InvoicesComponent {
  override error = linkedSignal(() => this.kycInvoiceApiStore.error());
  override messages = linkedSignal(() => this.kycInvoiceApiStore.messages());
  override success = linkedSignal(() => this.kycInvoiceApiStore.success());

  override invoicesTableSignal = linkedSignal(() => this.kycInvoiceApiStore.dataPage());

  constructor() {
    super();
    this.invoicesTablePaged.set(true);
  }

  override beforeOnInit(form: InvoicesVarsForm): InvoicesVarsForm {
    return form;
  }

  override doNgAfterViewInit(): void {
    this.invoicesTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        this.doSearch(paginator.pageIndex, paginator.pageSize);
      },
    });

    this.doSearch();
  }

  override beforeInvoicesSearch(form: any): void {

    this.doSearch();
  }

  doNgOnDestroy(): void { }

  private doSearch(pageNumber: number = 0, pageSize: number = 10): void {
    let value = this.invoicesForm.value;

    let criteria = new SearchObject<InvoiceSearchCriteria>();
    criteria.pageNumber = pageNumber;
    criteria.pageSize = pageSize;
    criteria.criteria = {
      ref: value.ref,
      organisatonId: value?.organisation?.id,
      paid: value.paid,
    };

    this.kycInvoiceApiStore.pagedSearch({
      criteria: criteria,
    });
  }
}
