// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.invoice;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class KycInvoiceApiImpl extends KycInvoiceApiBase {
    
    public KycInvoiceApiImpl(
        KycInvoiceService kycInvoiceService    ) {
        
        super(
            kycInvoiceService        );
    }



    @Override
    public ResponseEntity<KycInvoiceDTO> handleFindById(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> handleGetAll() throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<KycInvoiceDTO>> handleGetAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<KycInvoiceDTO>> handlePagedSearch(String criteria, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> handleRemove(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<KycInvoiceDTO> handleSave(KycInvoiceDTO invoice) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> handleSearch(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
}