// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.invoice;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.PropertySearchOrder;
import bw.co.centralkyc.SearchObject;

@RestController
public class KycInvoiceApiImpl implements KycInvoiceApi {

    private final KycInvoiceService kycInvoiceService;
    
    public KycInvoiceApiImpl(KycInvoiceService kycInvoiceService) {
        
        this.kycInvoiceService = kycInvoiceService;
    }

    @Override
    public ResponseEntity<KycInvoiceDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(kycInvoiceService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(kycInvoiceService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<KycInvoiceDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(kycInvoiceService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Page<KycInvoiceDTO>> pagedSearch(SearchObject<InvoiceSearchCriteria> criteria) throws Exception {
        try {
            return ResponseEntity.ok(kycInvoiceService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(kycInvoiceService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<KycInvoiceDTO> save(KycInvoiceDTO invoice) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(invoice, authentication);
            return ResponseEntity.ok(kycInvoiceService.save(invoice));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> search(SearchObject<InvoiceSearchCriteria> criteria) throws Exception {
        try {

            Set<PropertySearchOrder> sortOrders = new HashSet<>();
            if(criteria.getSortings() != null){
                sortOrders.addAll(criteria.getSortings());
            }

            return ResponseEntity.ok(kycInvoiceService.search(criteria.getCriteria(), sortOrders));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<KycInvoiceDTO> upload(String id, UploadPurpose purpose, MultipartFile file)
            throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'upload'");
    }

    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> generateInvoice(String subscriptionId) throws Exception {
        
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            String username = "anonymousUser";
            if(authentication != null) {

                username = authentication.getName();
            }

            return ResponseEntity.ok(kycInvoiceService.generateInvoice(subscriptionId, username));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> findByOrganisation(String organisationId) throws Exception {
        
        try {

            return ResponseEntity.ok(kycInvoiceService.findByOrganisation(organisationId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycInvoiceDTO>> findBySubscription(String subscriptionId) throws Exception {
        
        try {

            return ResponseEntity.ok(kycInvoiceService.findBySubscription(subscriptionId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Page<KycInvoiceDTO>> findByOrganisationPaged(String organisationId, Integer pageNumber,
            Integer pageSize) throws Exception {
        
        try {

            return ResponseEntity.ok(kycInvoiceService.findByOrganisation(organisationId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycInvoiceDTO>> findBySubscriptionPaged(String subscriptionId, Integer pageNumber,
            Integer pageSize) throws Exception {
        
        try {

            return ResponseEntity.ok(kycInvoiceService.findBySubscription(subscriptionId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        }
    }
}