// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Input, linkedSignal, Signal } from '@angular/core';
import { EditSubscriptionComponent } from '@app/view/subscription/edit-subscription.component';
import { EditSubscriptionVarsForm } from '@app/view/subscription/edit-subscription.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';

@Component({
  selector: 'app-edit-subscription',
  templateUrl: './edit-subscription.component.html',
  styleUrls: ['./edit-subscription.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class EditSubscriptionImplComponent extends EditSubscriptionComponent {

  @Input() id: string | any;

  override loading = linkedSignal(() => this.kycSubscriptionApiStore.loading());

  constructor() {
    super();

    this.kycSubscriptionApiStore.reset();
    if (this.id) {
      this.kycSubscriptionApiStore.findById({ id: this.id });
    }
  }

  override beforeOnInit(form: EditSubscriptionVarsForm): EditSubscriptionVarsForm {
    return form;
  }

  doNgOnDestroy(): void {}

  override beforeEditSubscriptionSave(form: any): void {
    this.kycSubscriptionApiStore.save({ subscription: this.editSubscriptionForm.value });
  }
}
