import { KycSubscriptionDTO } from './../../model/bw/co/centralkyc/subscription/kyc-subscription-dto';
// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, effect, inject, Input, linkedSignal, Signal } from '@angular/core';
import { EditSubscriptionComponent } from '@app/view/subscription/edit-subscription.component';
import { EditSubscriptionVarsForm } from '@app/view/subscription/edit-subscription.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';
import { OrganisationListDTO } from '@app/model/bw/co/centralkyc/organisation/organisation-list-dto';
import { OrganisationApiStore } from '@app/store/bw/co/centralkyc/organisation/organisation-api.store';
import { OrganisationSearchCriteria } from '@app/model/bw/co/centralkyc/organisation/organisation-search-criteria';
import { SearchObject } from '@app/model/search-object';

@Component({
  selector: 'app-edit-subscription',
  templateUrl: './edit-subscription.component.html',
  styleUrls: ['./edit-subscription.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class EditSubscriptionImplComponent extends EditSubscriptionComponent {
  organisationApiStore = inject(OrganisationApiStore);

  @Input() id: string | any;

  override loading = linkedSignal(() => this.kycSubscriptionApiStore.loading());
  override error = linkedSignal(() => this.kycSubscriptionApiStore.error());
  override messages = linkedSignal(() => this.kycSubscriptionApiStore.messages());
  override success = linkedSignal(() => this.kycSubscriptionApiStore.success());

  override organisationDisplays: string[] = ['name'];

  constructor() {
    super();

    this.kycSubscriptionApiStore.reset();
    if (this.id) {
      this.kycSubscriptionApiStore.findById({ id: this.id });
    }

    effect(() => {
      const organisations = this.organisationApiStore.dataList();
      this.organisationFilteredList.set(organisations);
    });

    effect(() => {
      let subscription = this.kycSubscriptionApiStore.data();
      if (subscription) {
        this.editSubscriptionForm.patchValue({
          id: subscription.id,
          createdBy: subscription.createdBy,
          createdAt: subscription.createdAt ? new Date(subscription.createdAt) : null,
          modifiedBy: subscription.modifiedBy,
          modifiedAt: subscription.modifiedAt ? new Date(subscription.modifiedAt) : null,
          amount: subscription.amount,
          ref: subscription.ref,
          organisation: subscription.organisationId
            ? this.organisationApiStore.dataList().find((org) => org.id === subscription.organisationId)
            : null,
          status: subscription.status,
          startDate: subscription.startDate ? new Date(subscription.startDate) : null,
          endDate: subscription.endDate ? new Date(subscription.endDate) : null,
          period: subscription.period,
        });

      }
    });
  }

  override beforeOnInit(form: EditSubscriptionVarsForm): EditSubscriptionVarsForm {

    this.route.queryParams.subscribe((params) => {
      const id = params['id'];
      if (id) {
        this.kycSubscriptionApiStore.findById({ id: id });
        let search = new SearchObject<OrganisationSearchCriteria>();
        search.criteria = {
          id: id,
        };

        this.organisationApiStore.search({
          criteria: search,
        });
      }
    });

    return form;
  }

  doNgOnDestroy(): void { }

  override beforeEditSubscriptionSave(form: any): void {
    let formValue = this.editSubscriptionForm.value;

    let subscription = new KycSubscriptionDTO();
    subscription.id = formValue.id;
    subscription.ref = formValue.ref;
    subscription.organisationName = formValue.organisation?.name;
    subscription.organisationId = formValue.organisation?.id;
    subscription.organisationCode = formValue.organisation?.code;
    subscription.organisationRegistrationNo = formValue.organisation?.registrationNo;
    subscription.status = formValue.status;
    subscription.startDate = formValue.startDate;
    subscription.endDate = formValue.endDate;
    subscription.amount = formValue.amount;
    subscription.period = formValue.period;
    subscription.createdBy = formValue.createdBy;
    subscription.createdAt = formValue.createdAt;
    subscription.modifiedBy = formValue.modifiedBy;
    subscription.modifiedAt = formValue.modifiedAt;

    this.kycSubscriptionApiStore.save({ subscription });
  }

  override organisationCompare(o1: OrganisationListDTO | any, o2: OrganisationListDTO | any) {
    return o1 && o2 ? o1.id === o2.id : o1 === o2;
  }

  override filterOrganisation() {
    const filterValue = this.organisationFilterCtrl.value?.toLowerCase() || '';
    let search = new SearchObject<OrganisationSearchCriteria>();
    search.criteria = {
      name: filterValue,
    };

    this.organisationApiStore.search({
      criteria: search,
    });
  }
}
