// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SubscriptionsComponent } from '@app/view/subscription/subscriptions.component';
import { SubscriptionsVarsForm } from '@app/view/subscription/subscriptions.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@app/@shared/loader/loader.component";

@Component({
  selector: 'app-subscriptions',
  templateUrl: './subscriptions.component.html',
  styleUrls: ['./subscriptions.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class SubscriptionsImplComponent extends SubscriptionsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SubscriptionsVarsForm): SubscriptionsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}