// Generated by andromda-angular cartridge (view\view.component.ts.vsl) DO NOT EDIT
import {
  Component,
  OnInit,
  effect,
  inject,
  ViewChild,
  Input,
  AfterViewInit,
  signal,
  Signal,
  linkedSignal,
  WritableSignal,
  OnDestroy,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import {
  FormBuilder,
} from '@angular/forms';
import { CurrencyPipe, DatePipe, formatDate } from '@angular/common';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { Subscription } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';
import { TableComponent } from '@app/components/table/table.component';
import { KycSubscriptionApiStore } from '@app/store/bw/co/centralkyc/subscription/kyc-subscription-api.store';
import { ColumnModel } from '@app/model/column.model';
import { ActionTemplate } from '@app/model/action-template';

import { KycSubscriptionControllerImpl } from '@app/controller/subscription/kyc-subscription-controller.impl';
import { TimePeriod } from '@app/model/bw/co/centralkyc/time-period';
import { KycInvoiceDTO } from '@app/model/bw/co/centralkyc/invoice/kyc-invoice-dto';
import { KycSubsciptionStatus } from '@app/model/bw/co/centralkyc/subscription/kyc-subsciption-status';
import { ToastrService } from 'ngx-toastr';
import { Page } from '@app/model/page.model';

export class SubscriptionDetailsVarsForm {
  id?: string | any;
  createdAt?: Date | any;
  createdBy?: string | any;
  modifiedAt?: Date | any;
  modifiedBy?: string | any;
  ref?: string | any;
  status?: KycSubsciptionStatus | any;
  organisationId?: string | any;
  organisationCode?: string | any;
  organisationName?: string | any;
  period?: TimePeriod | any;
  startDate?: Date | any;
  endDate?: Date | any;
  amount?: number | any;
  organisationRegistrationNo?: string | any;
}

@Component({
  selector: 'app-subscription-details-base',
  template: ''
})
export abstract class SubscriptionDetailsComponent implements OnInit, AfterViewInit, OnDestroy {

  separatorKeysCodes: number[] = [ENTER, COMMA];
  @Input() subscriptionDetailsVarsForm: SubscriptionDetailsVarsForm = {};

  // subscriptionDetailsForm: FormGroup = new FormGroup({});
  hide: boolean = false;
  protected route: ActivatedRoute = inject(ActivatedRoute);
  protected router: Router = inject(Router);
  protected formBuilder: FormBuilder = inject(FormBuilder);
  protected useCaseScope: UseCaseScope = inject(UseCaseScope);
  dialog: MatDialog = inject(MatDialog);
  toaster: ToastrService = inject(ToastrService);
  kycSubscriptionController: KycSubscriptionControllerImpl = inject(KycSubscriptionControllerImpl);
  readonly kycSubscriptionApiStore = inject(KycSubscriptionApiStore);
  @ViewChild('invoicesTable') invoicesTable?: TableComponent<KycInvoiceDTO>;
  invoicesTableSignal: Signal<any | KycInvoiceDTO | Page<KycInvoiceDTO>> = signal(null);
  invoicesTablePaged: WritableSignal<boolean> = linkedSignal(() => true);

  datePipe = inject(DatePipe);
  currencyPipe = inject(CurrencyPipe);

  invoicesTableColumns: ColumnModel[] = [
    new ColumnModel(
      'issueDate',
      'issue.date',
      false,
      undefined,
      this.datePipe,
      ['dd/MM/yyyy']
    ),
    new ColumnModel(
      'ref',
      'ref',
      false,
    ),
    new ColumnModel(
      'amount',
      'amount',
      false,
      undefined,
      this.currencyPipe,
      ['BWP']
    ),
    new ColumnModel(
      'paid',
      'paid',
      false,
    ),
    new ColumnModel(
      'payDate',
      'pay.date',
      false,
      undefined,
      this.datePipe,
      ['dd/MM/yyyy']
    ),
  ];

  invoicesTableColumnsActions: ActionTemplate[] = [
    {
      id: 'kyc-subscription-details',
      label: 'details',
      icon: 'remove_red_eye',
      tooltip: 'details',
    },
  ];

  showInvoicesActions = true;


  TimePeriodT: any = TimePeriod;
  TimePeriodOptions = Object.keys(this.TimePeriodT);
  KycSubsciptionStatusT: any = KycSubsciptionStatus;
  KycSubsciptionStatusOptions = Object.keys(this.KycSubsciptionStatusT);
  loaderMessage: Signal<string> = signal('');
  messages: Signal<string[]> = signal([]);
  success: Signal<boolean> = signal(false);
  loading: Signal<boolean> = signal(false);
  error: Signal<boolean> = signal(false);
  selected: Signal<any> = signal(null);

  subscriptionDetailsFormValueSubscription?: Subscription;

  constructor() {


    effect(() => {
      let messages = this.messages();

      if (this.success() && !this.loading()) {
        this.toaster.success(messages[0]);
      }

      if (this.error() && !this.loading()) {
        this.toaster.error(messages[0]);
      }
    })
  }

  abstract beforeOnInit(form: SubscriptionDetailsVarsForm): SubscriptionDetailsVarsForm;

  ngOnInit() {

    this.beforeOnInit(this.subscriptionDetailsVarsForm);

    this.afterOnInit();
  }

  handleFormChanges(change: any): void {

  }

  subscriptionDetailsFormReset() {

    if (this.router.url.substring(0, this.router.url.indexOf('?'))) {
      this.router.navigate([this.router.url.substring(0, this.router.url.indexOf('?'))]);
    } else {
      this.router.navigate([this.router.url]);
    }
  }

  afterOnInit(): void { }

  doNgAfterViewInit(): void { }

  ngAfterViewInit() {
    this.doNgAfterViewInit();
    this.kycSubscriptionController.resetUseCaseScope();
  }

  abstract doNgOnDestroy(): void;

  ngOnDestroy() {
    this.doNgOnDestroy();
    if (this.subscriptionDetailsFormValueSubscription) {
      this.subscriptionDetailsFormValueSubscription.unsubscribe();
    }
  }


  /**
   * This method may be overwritten
   */
  beforeSubscriptionDetailsEdit(form: any): void { }

  /**
   * This method may be overwritten
   */
  afterSubscriptionDetailsEdit(form: any): void { }

  /**
   * This method may be overwritten
   */
  get subscriptionDetailsEditId(): string {
    return {} as string;
  }

  subscriptionDetailsEdit(): void {

    let form: any = {
      id: this.subscriptionDetailsEditId,
    };

    this.beforeSubscriptionDetailsEdit(form);

    this.kycSubscriptionController.subscriptionDetailsEdit(form.id);
    this.afterSubscriptionDetailsEdit(form);
  }

  doSubscriptionDetailsDetails(form: any): any {

    console.log('SubscriptionDetailsDetails', form);
    this.router.navigate(['/invoice/details'], { queryParams: { id: form.row.id } });
    return form;
  }

  invoicesTableActionClicked(event: any): void {

    let form: any = {};
    let queryParams: any = {};
    let params: any = {};

    switch (event.action) {
      case 'kyc-subscription-details':
        // TODO: Implement the action
        form = {
          id: event.row.id,
        };
        queryParams = {
          id: event.row.id,
        };
        this.kycSubscriptionController.setQueryParams(Object.assign({}, queryParams));
        params = this.doSubscriptionDetailsDetails(event);
        this.useCaseScope.pageVariables = Object.assign({}, params);
        this.kycSubscriptionController.subscriptionDetailsDetails(
          event.id,
        );
        break;
    }
  }
}
