import { MatPaginator } from '@angular/material/paginator';
// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, inject, linkedSignal } from '@angular/core';
import { SubscriptionsComponent } from '@app/view/subscription/subscriptions.component';
import { SubscriptionsVarsForm } from '@app/view/subscription/subscriptions.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from '@app/@shared/loader/loader.component';
import { ColumnModel } from '@app/model/column.model';
import { pipe } from 'rxjs';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-subscriptions',
  templateUrl: './subscriptions.component.html',
  styleUrls: ['./subscriptions.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
  providers: [DatePipe, CurrencyPipe],
})
export class SubscriptionsImplComponent extends SubscriptionsComponent {
  override error = linkedSignal(() => this.kycSubscriptionApiStore.error());
  override messages = linkedSignal(() => this.kycSubscriptionApiStore.messages());
  override success = linkedSignal(() => this.kycSubscriptionApiStore.success());

  datePipe = inject(DatePipe);
  currencyPipe = inject(CurrencyPipe)

  override subscriptionsTableSignal = linkedSignal(() => this.kycSubscriptionApiStore.dataPage());

  override subscriptionsTableColumns: ColumnModel[] = [
    new ColumnModel('ref', 'ref', false),
    new ColumnModel('organisationName', 'organisation.name', false),
    new ColumnModel('startDate', 'start.date', false, undefined, this.datePipe, ['dd-MM-yyyy']),
    new ColumnModel('endDate', 'end.date', false, undefined, this.datePipe, ['dd-MM-yyyy']),
    new ColumnModel('amount', 'amount', false, undefined, this.currencyPipe, ['BWP']),
  ];

  constructor() {
    super();
  }

  override beforeOnInit(form: SubscriptionsVarsForm): SubscriptionsVarsForm {
    this.kycSubscriptionApiStore.reset();
    return form;
  }

  doNgOnDestroy(): void {}

  override doNgAfterViewInit(): void {
    this.subscriptionsTable?.tablePaginator?.page?.subscribe({
      next: (paginator: MatPaginator) => {
        this.doSearch(paginator.pageIndex, paginator.pageSize);
      },
    });

    this.doSearch();
  }

  private doSearch(pageNumber: number = 0, pageSize: number = 10): void {
    let value = this.criteriaControl.value || '';

    this.kycSubscriptionApiStore.pagedSearch({
      criteria: value,
      pageNumber: pageNumber,
      pageSize: pageSize,
    });
  }

  override beforeSubscriptionsSearch(form: any): void {
    this.doSearch();
  }
}
