// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.individual.kyc;

import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

@org.springframework.web.bind.annotation.RestController
public class KycRecordApiImpl extends KycRecordApiBase {
    
    public KycRecordApiImpl(
        bw.co.centralkyc.individual.kyc.KycRecordService kycRecordService    ) {
        
        super(
            kycRecordService        );
    }


    @Override
    public ResponseEntity<bw.co.centralkyc.individual.kyc.KycRecordDTO> handleFindById(java.lang.String id) {
        RestApiResponse<bw.co.centralkyc.individual.kyc.KycRecordDTO> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<bw.co.centralkyc.individual.kyc.KycRecordDTO>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> handleFindByIdentityNo(java.lang.String identityNo) {
        RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> handleFindByIndividual(java.lang.String individualId) {
        RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> handleGetAll() {
        RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<org.springframework.data.domain.Page<bw.co.centralkyc.individual.kyc.KycRecordDTO>> handleGetAllPaged(java.lang.Integer pageNumber, java.lang.Integer pageSize) {
        RestApiResponse<org.springframework.data.domain.Page<bw.co.centralkyc.individual.kyc.KycRecordDTO>> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<org.springframework.data.domain.Page<bw.co.centralkyc.individual.kyc.KycRecordDTO>>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<org.springframework.data.domain.Page<bw.co.centralkyc.individual.kyc.KycRecordDTO>> handlePagedSearch(java.lang.String criteria, java.lang.Integer pageNumber, java.lang.Integer pageSize) {
        RestApiResponse<org.springframework.data.domain.Page<bw.co.centralkyc.individual.kyc.KycRecordDTO>> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<org.springframework.data.domain.Page<bw.co.centralkyc.individual.kyc.KycRecordDTO>>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<java.lang.Boolean> handleRemove(java.lang.String id) {
        RestApiResponse<java.lang.Boolean> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<java.lang.Boolean>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<bw.co.centralkyc.individual.kyc.KycRecordDTO> handleSave(bw.co.centralkyc.individual.kyc.KycRecordDTO kycRecord) {
        RestApiResponse<bw.co.centralkyc.individual.kyc.KycRecordDTO> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<bw.co.centralkyc.individual.kyc.KycRecordDTO>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }

    @Override
    public ResponseEntity<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> handleSearch(java.lang.String criteria) {
        RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>> responseData = new RestApiResponse<>();
        responseData.setData(null);
        responseData.setStatus(HttpStatus.OK.value());
        responseData.setMessage(String.format("Operation successful."));
        ResponseEntity<RestApiResponse<java.util.Collection<bw.co.centralkyc.individual.kyc.KycRecordDTO>>> response = ResponseEntity.status(HttpStatus.OK).body(responseData);

        return response;
    }
}