// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.individual.kyc;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import bw.co.centralkyc.AuditTracker;

import java.util.Collection;

import org.springframework.data.domain.Page;

@org.springframework.web.bind.annotation.RestController
public class KycRecordApiImpl extends KycRecordApiBase {

    public KycRecordApiImpl(KycRecordService kycRecordService) {

        super(kycRecordService);
    }

    @Override
    public ResponseEntity<KycRecordDTO> handleFindById(String id) throws Exception {

        try {

            return ResponseEntity.ok(kycRecordService.findById(id));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> handleFindByIdentityNo(String identityNo)
            throws Exception {

        try {

            return ResponseEntity.ok(kycRecordService.findByIdentityNo(identityNo));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> handleFindByIndividual(String individualId)
            throws Exception {

        try {
            
            return ResponseEntity.ok(kycRecordService.findByIndividual(individualId));

        } catch (Exception e) {

            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> handleGetAll() throws Exception {

        try {
            return ResponseEntity.ok(kycRecordService.getAll());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordDTO>> handleGetAllPaged(Integer pageNumber, Integer pageSize)
            throws Exception {

        try {
            return ResponseEntity.ok(kycRecordService.getAll(pageNumber, pageSize));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Page<KycRecordDTO>> handlePagedSearch(String criteria, Integer pageNumber,
            Integer pageSize) throws Exception {

        try {
            return ResponseEntity.ok(kycRecordService.search(criteria, pageNumber, pageSize));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Boolean> handleRemove(String id) throws Exception {
        try {
            return ResponseEntity.ok(kycRecordService.remove(id));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<KycRecordDTO> handleSave(KycRecordDTO kycRecord) throws Exception {
        try {
            
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(kycRecord, authentication);

            return ResponseEntity.ok(kycRecordService.save(kycRecord));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<Collection<KycRecordDTO>> handleSearch(String criteria) throws Exception {
        try {
            
            return ResponseEntity.ok(kycRecordService.search(criteria));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
}