// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.centralkyc.settings;

import bw.co.centralkyc.AuditTracker;
import bw.co.centralkyc.RestApiResponse;
import bw.co.centralkyc.TargetEntity;
import bw.co.centralkyc.document.DocumentApi;
import bw.co.centralkyc.document.DocumentDTO;

import java.util.Collection;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class SettingsApiImpl extends SettingsApiBase {

    private final DocumentApi documentApi;

    public SettingsApiImpl(SettingsService settingsService, DocumentApi documentApi) {

        super(settingsService);
        this.documentApi = documentApi;
    }

    @Override
    public ResponseEntity<SettingsDTO> handleFindById(String id) {
        try {

            return ResponseEntity.ok(null);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<SettingsDTO>> handleGetAll() {
        try {
            return ResponseEntity.ok(settingsService.getAll());

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Page<SettingsDTO>> handleGetAllPaged(Integer pageNumber, Integer pageSize) {
        try {
            return ResponseEntity.ok(settingsService.getAll(pageNumber, pageSize));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Page<SettingsDTO>> handlePagedSearch(String criteria, Integer pageNumber,
            Integer pageSize) {
        try {
            return ResponseEntity.ok(null);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Boolean> handleRemove(String id) {
        try {
            return ResponseEntity.ok(false);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<SettingsDTO> handleSave(SettingsDTO setttings) {
        try {

            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(setttings, authentication);

            return ResponseEntity.ok(
                    settingsService.save(setttings));

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<Collection<SettingsDTO>> handleSearch(String criteria) {
        try {
            return ResponseEntity.ok(null);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }

    }

    @Override
    public ResponseEntity<SettingsDTO> handleUploadTemplate(MultipartFile template, TargetEntity target)
            throws Exception {

        try {

            if(target != TargetEntity.INVOICE && target != TargetEntity.QUOTATION) {
                throw new IllegalArgumentException("Invalid target entity for template upload: " + target);
            }

            SettingsDTO settings = settingsService.getAll().stream().findFirst()
                    .orElseThrow(() -> new Exception("Settings not found"));

            DocumentDTO doc = documentApi
                    .upload(
                            target,
                            settings.getId(),
                            target == TargetEntity.INVOICE ? settings.getInvoiceDocumentType().getId()
                                    : settings.getQuotationDocumentType().getId(),
                            template)
                    .getBody();

            if(target == TargetEntity.INVOICE) {

                settings.setInvoiceTemplate(doc);
            } else if (target == TargetEntity.QUOTATION) {
                
                settings.setQuotationTemplate(doc);
            }

            return this.save(settings);

        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<SettingsDTO> handleAttachDocumentType(String documentTypeId, DocumentTypePurpose purpose)
            throws Exception {
        

        try {
            return ResponseEntity.ok(settingsService.attachDocumentType(documentTypeId, purpose));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    @Override
    public ResponseEntity<SettingsDTO> handleDetachDocumentType(String documentTypeId, DocumentTypePurpose purpose)
            throws Exception {
        
        try {
            return ResponseEntity.ok(settingsService.detachDocumentType(documentTypeId, purpose));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
}