// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { SettingsController } from '@app/controller/settings/settings-controller';

@Injectable()
export class SettingsControllerImpl extends SettingsController {

    constructor() {
        super();
    }

}
