// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.centralkyc.organisation.document;

import bw.co.centralkyc.document.type.DocumentTypeMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        DocumentTypeMapper.class    }
)
public interface OrganisationDocumentMapper {
    
    /**
     * Converts this entity to an object of type {@link OrganisationDocumentDTO}.
     * @param entity
     * @return OrganisationDocumentDTO
     */
    @Mapping(target = "documentTypeId", source = "documentType.id")
    @Mapping(target = "documentType", source = "documentType.name")
    OrganisationDocumentDTO toOrganisationDocumentDTO(OrganisationDocument entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link OrganisationDocumentDTO}.
     * @param entities
     * @return Collection<OrganisationDocumentDTO>     */
    List<OrganisationDocumentDTO> toOrganisationDocumentDTOCollection(Collection<OrganisationDocument> entities);

    /**
     * Converts an instance of type {@link OrganisationDocumentDTO} to this DAO's entity.
     * @param organisationDocumentDTO
     * @return OrganisationDocument
     */
    @Mapping(target = "documentType", ignore = true)
    OrganisationDocument organisationDocumentDTOToEntity(OrganisationDocumentDTO organisationDocumentDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "documentType", ignore = true)
    void updateOrganisationDocumentFromOrganisationDocumentDTO(OrganisationDocumentDTO organisationDocumentDTO, @MappingTarget OrganisationDocument entity);

}